# Generated by coh-rtc. DO NOT EDIT BY HAND.
# Author: Lukas Bower
# Purpose: Provide manifest-derived defaults for the Cohesix Python client.
# Copyright 2026 Lukas Bower

DEFAULTS = {
    "placeholder_credentials": ["changeme", "bootstrap", "worker", "worker-gpu", "worker-bus", "worker-lora", "password", "secret", "default", "placeholder", "replace-me", "your-token", "your-token-here"],
    "authority": {"production": False, "delegated_rest": True, "identity_class": "gateway_enforced", "strict_queen_intents": True, "legacy_queen_ctl": True, "writer_epoch": 1, "writer_epoch_required": False, "queen_intent_schema": "queen-intent/v1", "queen_intent_path": "/queen/intents/ctl", "queen_dedupe_path": "/proc/queen/dedupe", "queen_intent_max_bytes": 2048},
    "host_snapshots": {"enable": True, "max_bytes": 8192, "max_entries": 64, "max_value_bytes": 1024, "max_ttl_ms": 30000, "publishers": [
        {"source_id": "linux-reference", "providers": ["systemd", "docker", "k8s", "nvidia", "jetson", "network"]},
        {"source_id": "mac-controller", "providers": ["launchd", "network"]},
    ]},
    "contract_kind": "target-neutral-fallback",
    "manifest_sha256": None,
    "generation_source_sha256": "33ac378131c163399b747dac5175baf2619a92674de81f5ed3f8cf4e649f4de6",
    "execution_proof": "none",
    "diagnostic_artifacts": {"max_bytes": 1048576, "max_files": 682, "trace_max_duration_ms": 60000},
    "secure9p": {"msize": 8192, "walk_depth": 8},
    "console": {
        "max_line_len": 2304,
        "max_path_len": 96,
        "max_json_len": 192,
        "max_id_len": 32,
        "max_echo_len": 2048,
        "max_ticket_len": 224,
        "cat_chunk_max_count": 64,
        "cat_chunk_max_wire_bytes": 256,
        "cat_reassembled_max_bytes": 8192,
    },
    "ticket_limits": {
        "max_scopes": 8,
        "max_scope_path_len": 128,
        "max_scope_rate_per_s": 64,
        "bandwidth_bytes": 8388608,
        "cursor_resumes": 16,
        "cursor_advances": 256,
    },
    "paths": {
        "queen_ctl": "/queen/ctl",
        "queen_lifecycle_ctl": "/queen/lifecycle/ctl",
        "queen_schedule_ctl": "/queen/schedule/ctl",
        "queen_lease_ctl": "/queen/lease/ctl",
        "queen_export_ctl": "/queen/export/ctl",
        "policy_ctl": "/policy/ctl",
        "log": "/log/queen.log",
    },
    "control_plane": {
        "schedule": {
            "enable": True,
            "queue_max_entries": 256,
            "ctl_max_bytes": 8192,
        },
        "lease": {
            "enable": True,
            "active_max_entries": 256,
            "preemptions_max_entries": 256,
            "ctl_max_bytes": 8192,
        },
        "export": {
            "enable": True,
            "ctl_max_bytes": 2048,
        },
    },
    "observability": {
        "proc_schedule": {
            "summary": True,
            "queue": True,
            "summary_bytes": 128,
            "queue_bytes": 256,
        },
        "proc_lease": {
            "summary": True,
            "active": True,
            "preemptions": True,
            "summary_bytes": 160,
            "active_bytes": 256,
            "preemptions_bytes": 256,
        },
    },
    "telemetry_ingest": {
        "max_segments_per_device": 4,
        "max_bytes_per_segment": 131072,
        "max_total_bytes_per_device": 524288,
        "max_reference_entries_per_segment": 1024,
        "max_reference_manifest_bytes_per_segment": 131072,
        "max_reference_bytes_per_segment": 1073741824,
        "eviction_policy": "evict-oldest",
    },
    "telemetry_push": {
        "schema": "cohsh-telemetry-push/v1",
        "max_record_bytes": 4096,
    },
    "coh": {
        "mount": {
            "root": "/",
            "allowlist": [
                "/proc",
                "/queen",
                "/shard",
                "/worker",
                "/log",
                "/gpu",
                "/host"
            ]
        },
        "telemetry": {
            "root": "/queen/telemetry",
            "max_devices": 32,
            "max_segments_per_device": 4,
            "max_bytes_per_segment": 131072,
            "max_total_bytes_per_device": 524288,
        },
        "run": {
            "lease": {
                "schema": "gpu-lease/v1",
                "active_state": "ACTIVE",
                "max_bytes": 1024,
            },
            "breadcrumb": {
                "schema": "gpu-breadcrumb/v1",
                "max_line_bytes": 512,
                "max_command_bytes": 256,
            },
        },
        "peft": {
            "export": {
                "root": "/queen/export/lora_jobs",
                "max_telemetry_bytes": 131072,
                "max_policy_bytes": 8192,
                "max_base_model_bytes": 1024,
            },
            "import": {
                "registry_root": "out/model_registry",
                "max_adapter_bytes": 67108864,
                "max_lora_bytes": 65536,
                "max_metrics_bytes": 65536,
                "max_manifest_bytes": 8192,
            },
            "activate": {
                "max_model_id_bytes": 128,
                "max_state_bytes": 4096,
            },
        },
    },
    "retry": {
        "max_attempts": 3,
        "backoff_ms": 200,
        "ceiling_ms": 2000,
        "timeout_ms": 5000,
    },
    "examples": {
        "gpu_id": "GPU-0",
        "mig_gpu_id": "MIG-0",
        "job_id": "job_8932",
        "model_id": "llama3-edge-v7",
        "device_id": "device-1",
        "output_root": "out/examples",
    },
}

PROFILE_SCHEMA = "cohesix-python-profile/v2"
HOST_TICKET_REQUEST_SCHEMAS = ("host-ticket/v1", "host-ticket/v2")
HOST_TICKET_RESULT_SCHEMAS = ("host-ticket-result/v1", "host-ticket-result/v2")
GPU_RECEIPT_ACTIONS = ("gpu.lease.grant", "gpu.lease.renew", "gpu.lease.release", "gpu.workload.submit", "gpu.workload.cancel", "gpu.workload.observe")
PEFT_RECEIPT_ACTIONS = ("peft.export", "peft.import", "peft.activate", "peft.rollback", "peft.release")
