# Author: Lukas Bower
# Purpose: Configure the coh-rtc manifest compiler crate.
# Copyright 2026 Lukas Bower
[package]
name = "coh-rtc"
version = "0.1.0"
edition = "2021"
publish = false
default-run = "coh-rtc"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
ciborium = "0.2.2"
sha2 = { workspace = true }
hex = { workspace = true }
toml = "1.1.4"
cohesix-cas = { workspace = true }
cohsh-core = { workspace = true }
cohesix-ticket = { workspace = true }
ed25519-dalek = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
tempfile = "3.27.0"
