# Author: Lukas Bower
# Purpose: Define ratchet baseline counts for high-risk non-test Rust patterns tracked by due-diligence gates.
# Copyright 2026 Lukas Bower

[non_test]
unsafe = 691
unwrap = 286
expect = 703
panic = 115
