#!/usr/bin/env bash
###############################################################################
# cohesix_fix.sh – one-shot patcher for current Cohesix Rust repo
# * Creates a timestamped backup (tar.gz) so nothing is lost
# * Ensures src/utils.rs exists
# * Adds missing re-exports for Function + IRContext in src/ir/mod.rs
# * Pins clap 4 with the “deprecated” feature to keep legacy APIs working
# * Runs `cargo check --all-targets` and reports success or failures
###############################################################################
set -euo pipefail

echo "🔍 Detecting repo root…"
if ! [ -f Cargo.toml ]; then
  echo "❌ No Cargo.toml in $(pwd).  Please cd to the project root and re-run." >&2
  exit 1
fi

TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP="cohesix_backup_${TIMESTAMP}.tar.gz"
echo "🗄  Creating backup: ${BACKUP}"
tar -czf "${BACKUP}" . --exclude="${BACKUP}"

###############################################################################
# 1 · utils module
###############################################################################
if [ ! -f src/utils.rs ] && [ ! -d src/utils ]; then
  echo "ℹ️  Generating placeholder src/utils.rs"
  mkdir -p src
  cat > src/utils.rs <<'RS'
/// utils.rs – placeholder generated by cohesix_fix.sh
///
/// Replace these stubs with real helper functions or remove the module
/// declaration from `src/lib.rs` if it is no longer required.

pub fn todo_placeholder() {
    // TODO: implement or remove
}
RS
else
  echo "✅ utils module already present"
fi

###############################################################################
# 2 · IR re-exports
###############################################################################
IR_MOD="src/ir/mod.rs"
if [ -f "${IR_MOD}" ]; then
  if ! grep -q "pass_framework::ir_pass_framework::ir::IRContext" "${IR_MOD}"; then
    echo "ℹ️  Adding re-exports for Function & IRContext to ${IR_MOD}"
    printf '\n// --- Auto-generated re-exports (cohesix_fix.sh) ---\n' >> "${IR_MOD}"
    printf 'pub use crate::pass_framework::ir_pass_framework::ir::{Function, IRContext};\n' >> "${IR_MOD}"
  else
    echo "✅ IR re-exports already present"
  fi
else
  echo "⚠️  ${IR_MOD} not found; skipping IR re-export patch"
fi

###############################################################################
# 3 · clap dependency pin (v4 + deprecated feature)
###############################################################################
echo "🔧 Ensuring clap dependency uses \"deprecated\" feature…"
if grep -qE '^\s*clap\s*=' Cargo.toml; then
  # Comment out existing clap lines so Cargo sees only one entry
  sed -i.bak '/^\s*clap\s*=/{s/^/# AUTO-COMMENTED by cohesix_fix.sh /}' Cargo.toml
fi
echo 'clap = { version = "4.5.38", features = ["derive","deprecated"] }' >> Cargo.toml

###############################################################################
# 4 · Final build check
###############################################################################
echo "🚀 Running cargo check --all-targets …"
if cargo check --all-targets; then
  echo "🎉 Build clean. Red squiggles should vanish after VS Code reload."
else
  echo "❌ Build still failing. Scroll up for compiler errors."
fi
###############################################################################
echo "✅ cohesix_fix.sh completed. Backup stored as ${BACKUP}"
###############################################################################
