// Copyright 2026 Lukas Bower
// SPDX-License-Identifier: Apache-2.0
// Purpose: Provide bounded no_std worker-loop state machines for VM worker roles.
// Author: Lukas Bower

//! Bounded worker-loop primitives shared by VM worker roles.

/// Default heartbeat cadence used by the no_std heartbeat worker loop.
pub const DEFAULT_HEARTBEAT_INTERVAL_MS: u64 = 1_000;
const BADGE_EPOCH_BITS: u8 = 8;
const BADGE_ATTACH_BASE: u64 = 0x260c_1000;
const BADGE_TELEMETRY_BASE: u64 = 0x260c_2000;
const BADGE_LEASE_BASE: u64 = 0x260c_3000;
const BADGE_RECEIPT_BASE: u64 = 0x260c_4000;
const BADGE_REVOKE_BASE: u64 = 0x260c_5000;

/// Worker roles that may own a bounded loop instance.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum WorkerRole {
    /// Heartbeat telemetry worker.
    Heartbeat = 1,
    /// GPU control receipt worker.
    Gpu = 2,
    /// LoRA control receipt worker.
    Lora = 3,
}

impl WorkerRole {
    const fn badge_code(self) -> u8 {
        self as u8
    }
}

/// Five-part Worker identity used by the bounded host compatibility model.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WorkerIdentity {
    /// Role assigned to the worker.
    pub role: WorkerRole,
    /// Manifest-local Worker slot.
    pub slot: u32,
    /// Lease epoch associated with this worker authority.
    pub lease_epoch: u64,
    /// Generation of the root-owned supervisor instance.
    pub supervisor_generation: u64,
    /// Capability-bundle or endpoint-cap generation.
    pub cap_generation: u64,
}

impl WorkerIdentity {
    /// Create a worker identity.
    #[must_use]
    pub const fn new(
        role: WorkerRole,
        slot: u32,
        lease_epoch: u64,
        supervisor_generation: u64,
        cap_generation: u64,
    ) -> Self {
        Self {
            role,
            slot,
            lease_epoch,
            supervisor_generation,
            cap_generation,
        }
    }

    /// Return true when all generation-bearing identity components are present.
    #[must_use]
    pub const fn valid(self) -> bool {
        self.lease_epoch != 0 && self.supervisor_generation != 0 && self.cap_generation != 0
    }

    /// Return the deterministic attach badge expected on this worker's endpoint cap.
    #[must_use]
    pub const fn badge(self) -> WorkerBadge {
        self.badge_for(WorkerEndpointAction::Attach)
    }

    /// Return the deterministic badge for a worker endpoint action.
    #[must_use]
    pub const fn badge_for(self, action: WorkerEndpointAction) -> WorkerBadge {
        let role = (self.role.badge_code() as u64) << BADGE_EPOCH_BITS;
        let epoch = self.lease_epoch & ((1u64 << BADGE_EPOCH_BITS) - 1);
        WorkerBadge::from_raw(action.base().saturating_add(role | epoch))
    }
}

/// Worker endpoint-cap action classes generated by root-task.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WorkerEndpointAction {
    /// Attach the worker.
    Attach,
    /// Emit telemetry.
    Telemetry,
    /// Renew or expire a lease.
    Lease,
    /// Emit a control receipt.
    Receipt,
    /// Publish a revoke-sensitive event.
    Revoke,
}

impl WorkerEndpointAction {
    const fn base(self) -> u64 {
        match self {
            Self::Attach => BADGE_ATTACH_BASE,
            Self::Telemetry => BADGE_TELEMETRY_BASE,
            Self::Lease => BADGE_LEASE_BASE,
            Self::Receipt => BADGE_RECEIPT_BASE,
            Self::Revoke => BADGE_REVOKE_BASE,
        }
    }
}

/// Badged endpoint identity supplied by root-task.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WorkerBadge {
    raw: u64,
}

impl WorkerBadge {
    /// Build a badge from its raw seL4 badge value.
    #[must_use]
    pub const fn from_raw(raw: u64) -> Self {
        Self { raw }
    }

    /// Return the raw badge value.
    #[must_use]
    pub const fn raw(self) -> u64 {
        self.raw
    }

    /// Return true when the badge matches the supplied identity.
    #[must_use]
    pub const fn matches_identity(self, identity: WorkerIdentity) -> bool {
        self.raw == identity.badge().raw()
    }
}

/// Endpoint capability visible to a worker loop.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EndpointCap {
    cptr: u64,
    badge: WorkerBadge,
}

impl EndpointCap {
    /// Create an endpoint capability model with a non-zero CPtr and badge.
    pub const fn new(cptr: u64, badge: WorkerBadge) -> Result<Self, WorkerLoopError> {
        if cptr == 0 {
            return Err(WorkerLoopError::InvalidEndpointCap);
        }
        if badge.raw() == 0 {
            return Err(WorkerLoopError::InvalidBadge);
        }
        Ok(Self { cptr, badge })
    }

    /// Return the endpoint CPtr.
    #[must_use]
    pub const fn cptr(self) -> u64 {
        self.cptr
    }

    /// Return the endpoint badge.
    #[must_use]
    pub const fn badge(self) -> WorkerBadge {
        self.badge
    }
}

/// Attach request delivered to a detached worker.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AttachRequest {
    /// Endpoint cap used for worker receipts and telemetry.
    pub endpoint: EndpointCap,
    /// Monotonic time when attach was admitted.
    pub now_ms: u64,
    /// Lease time-to-live for this worker authority.
    pub lease_ttl_ms: u64,
}

/// Pressure level reported by root-task notifications.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PressureLevel {
    /// Normal operation.
    Nominal,
    /// Nonessential output should be reduced.
    High,
    /// Only essential receipts should be attempted.
    Overload,
}

/// Lifecycle notifications delivered to an attached worker.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WorkerNotification {
    /// Revoke the current endpoint authority.
    Revoke {
        /// Monotonic event time.
        now_ms: u64,
    },
    /// Shut the worker down gracefully.
    Shutdown {
        /// Monotonic event time.
        now_ms: u64,
    },
    /// Renew the active lease.
    Lease {
        /// Monotonic renewal time.
        now_ms: u64,
        /// New lease time-to-live.
        ttl_ms: u64,
    },
    /// Publish pressure state.
    Pressure {
        /// Monotonic event time.
        now_ms: u64,
        /// Current pressure level.
        level: PressureLevel,
    },
}

impl WorkerNotification {
    fn now_ms(self) -> u64 {
        match self {
            Self::Revoke { now_ms }
            | Self::Shutdown { now_ms }
            | Self::Lease { now_ms, .. }
            | Self::Pressure { now_ms, .. } => now_ms,
        }
    }
}

/// Receipt classes emitted by control-only VM workers.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReceiptKind {
    /// Heartbeat telemetry receipt.
    Heartbeat,
    /// GPU control receipt; hardware execution remains host-side.
    GpuControl,
    /// LoRA control receipt; training execution remains host-side.
    LoraControl,
}

/// Receipt request admitted by the worker loop.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ReceiptRequest {
    /// Monotonic request time.
    pub now_ms: u64,
    /// Caller-supplied receipt identifier.
    pub receipt_id: u64,
    /// Receipt class being requested.
    pub kind: ReceiptKind,
}

/// Event consumed by a worker loop turn.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WorkerEvent {
    /// Attach a detached worker to a badged endpoint.
    Attach(AttachRequest),
    /// Poll the worker for bounded progress.
    Poll {
        /// Monotonic poll time.
        now_ms: u64,
    },
    /// Deliver a lifecycle notification.
    Notify(WorkerNotification),
    /// Request a receipt emission.
    Receipt(ReceiptRequest),
}

impl WorkerEvent {
    fn now_ms(self) -> u64 {
        match self {
            Self::Attach(request) => request.now_ms,
            Self::Poll { now_ms } => now_ms,
            Self::Notify(notification) => notification.now_ms(),
            Self::Receipt(request) => request.now_ms,
        }
    }
}

/// Worker lifecycle state.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WorkerState {
    /// No endpoint authority has been attached.
    Detached,
    /// Endpoint authority is active.
    Attached,
    /// Authority was explicitly revoked.
    Revoked,
    /// Worker received shutdown.
    Shutdown,
    /// Active lease expired.
    LeaseExpired,
}

impl WorkerState {
    /// Return true when no further telemetry or receipts may be emitted.
    #[must_use]
    pub const fn is_terminal(self) -> bool {
        matches!(self, Self::Revoked | Self::Shutdown | Self::LeaseExpired)
    }
}

/// Lifecycle events emitted through the endpoint.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LifecycleEvent {
    /// Attach was accepted.
    Attached,
    /// Active lease was renewed.
    LeaseRenewed,
    /// Active lease expired.
    LeaseExpired,
    /// Authority was revoked.
    Revoked,
    /// Shutdown was requested.
    Shutdown,
    /// Pressure state changed.
    Pressure(PressureLevel),
}

/// Telemetry records emitted by a worker loop.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TelemetryRecord {
    /// Heartbeat tick telemetry.
    Heartbeat {
        /// Monotonic event time.
        now_ms: u64,
        /// Worker-local heartbeat tick.
        tick: u64,
    },
}

/// Receipt records emitted by a worker loop.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ReceiptRecord {
    /// Monotonic emission time.
    pub now_ms: u64,
    /// Worker-local receipt sequence.
    pub sequence: u64,
    /// Caller-supplied receipt identifier.
    pub receipt_id: u64,
    /// Receipt class emitted.
    pub kind: ReceiptKind,
}

/// Lifecycle records emitted by a worker loop.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct LifecycleRecord {
    /// Monotonic emission time.
    pub now_ms: u64,
    /// Worker-local emission sequence.
    pub sequence: u64,
    /// Lifecycle event.
    pub event: LifecycleEvent,
}

/// Endpoint invocation payload produced by the state machine.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InvocationKind {
    /// Telemetry append or send operation.
    Telemetry(TelemetryRecord),
    /// Control receipt operation.
    Receipt(ReceiptRecord),
    /// Lifecycle event operation.
    Lifecycle(LifecycleRecord),
}

/// Badged endpoint invocation modeled by the worker loop.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct EndpointInvocation {
    /// Endpoint cap being invoked.
    pub endpoint: EndpointCap,
    /// Badge expected by the receiver for this invocation.
    pub badge: WorkerBadge,
    /// Worker-local emission sequence.
    pub sequence: u64,
    /// Invocation payload.
    pub kind: InvocationKind,
}

/// Progress classification for a single bounded worker turn.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WorkerProgress {
    /// Attach completed.
    Attached,
    /// A telemetry or receipt payload was emitted.
    Emitted,
    /// A lifecycle event was emitted.
    Lifecycle,
    /// The turn completed without output.
    Idle,
    /// The turn moved the worker into a terminal state.
    Terminal,
}

/// Result of one bounded worker turn.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct StepOutcome {
    /// Bounded progress made by this turn.
    pub progress: WorkerProgress,
    /// Optional endpoint invocation emitted by this turn.
    pub output: Option<EndpointInvocation>,
}

/// Summary returned by bounded multi-turn execution.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BoundedRun {
    /// Number of events processed.
    pub processed: usize,
    /// Number of endpoint invocations emitted.
    pub emitted: usize,
    /// True when the loop ended in a terminal worker state.
    pub terminal: bool,
    /// First error encountered, if any.
    pub error: Option<WorkerLoopError>,
}

/// Errors returned by the worker loop.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WorkerLoopError {
    /// A generation-bearing Worker identity contained a zero component.
    InvalidIdentity,
    /// Endpoint CPtr was zero.
    InvalidEndpointCap,
    /// Endpoint badge was zero.
    InvalidBadge,
    /// Endpoint badge did not match the worker identity.
    BadgeMismatch,
    /// Lease TTL was zero.
    InvalidLease,
    /// Lease expiry overflowed the monotonic clock.
    LeaseOverflow,
    /// Heartbeat interval was zero.
    InvalidHeartbeatInterval,
    /// Worker role did not match the requested loop mode.
    RoleMismatch,
    /// Event requires an attached endpoint.
    NotAttached,
    /// Attach was attempted after endpoint authority already existed.
    AlreadyAttached,
    /// Event was attempted after the worker reached a terminal state.
    TerminalState,
    /// Receipt kind does not match this worker loop.
    ReceiptMismatch,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
struct LeaseWindow {
    expires_at_ms: u64,
}

impl LeaseWindow {
    fn new(now_ms: u64, ttl_ms: u64) -> Result<Self, WorkerLoopError> {
        if ttl_ms == 0 {
            return Err(WorkerLoopError::InvalidLease);
        }
        let expires_at_ms = now_ms
            .checked_add(ttl_ms)
            .ok_or(WorkerLoopError::LeaseOverflow)?;
        Ok(Self { expires_at_ms })
    }

    fn is_expired(self, now_ms: u64) -> bool {
        now_ms >= self.expires_at_ms
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum WorkerMode {
    Heartbeat {
        interval_ms: u64,
        next_due_ms: u64,
        tick: u64,
    },
    Receipt {
        kind: ReceiptKind,
    },
}

impl WorkerMode {
    fn receipt_kind(self) -> Option<ReceiptKind> {
        match self {
            Self::Heartbeat { .. } => Some(ReceiptKind::Heartbeat),
            Self::Receipt { kind } => Some(kind),
        }
    }
}

/// Allocation-free worker-loop state machine.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WorkerLoop {
    identity: WorkerIdentity,
    state: WorkerState,
    endpoint: Option<EndpointCap>,
    lease: Option<LeaseWindow>,
    mode: WorkerMode,
    sequence: u64,
    pressure: PressureLevel,
}

impl WorkerLoop {
    /// Create a heartbeat worker loop.
    pub fn heartbeat(identity: WorkerIdentity, interval_ms: u64) -> Result<Self, WorkerLoopError> {
        if !identity.valid() {
            return Err(WorkerLoopError::InvalidIdentity);
        }
        if identity.role != WorkerRole::Heartbeat {
            return Err(WorkerLoopError::RoleMismatch);
        }
        if interval_ms == 0 {
            return Err(WorkerLoopError::InvalidHeartbeatInterval);
        }
        Ok(Self::new(
            identity,
            WorkerMode::Heartbeat {
                interval_ms,
                next_due_ms: 0,
                tick: 0,
            },
        ))
    }

    /// Create a GPU receipt-only worker loop.
    pub fn gpu_receipts(identity: WorkerIdentity) -> Result<Self, WorkerLoopError> {
        if !identity.valid() {
            return Err(WorkerLoopError::InvalidIdentity);
        }
        if identity.role != WorkerRole::Gpu {
            return Err(WorkerLoopError::RoleMismatch);
        }
        Ok(Self::new(
            identity,
            WorkerMode::Receipt {
                kind: ReceiptKind::GpuControl,
            },
        ))
    }

    /// Create a LoRA receipt-only worker loop.
    pub fn lora_receipts(identity: WorkerIdentity) -> Result<Self, WorkerLoopError> {
        if !identity.valid() {
            return Err(WorkerLoopError::InvalidIdentity);
        }
        if identity.role != WorkerRole::Lora {
            return Err(WorkerLoopError::RoleMismatch);
        }
        Ok(Self::new(
            identity,
            WorkerMode::Receipt {
                kind: ReceiptKind::LoraControl,
            },
        ))
    }

    fn new(identity: WorkerIdentity, mode: WorkerMode) -> Self {
        Self {
            identity,
            state: WorkerState::Detached,
            endpoint: None,
            lease: None,
            mode,
            sequence: 0,
            pressure: PressureLevel::Nominal,
        }
    }

    /// Return the identity bound to this worker loop.
    #[must_use]
    pub const fn identity(&self) -> WorkerIdentity {
        self.identity
    }

    /// Return the current worker state.
    #[must_use]
    pub const fn state(&self) -> WorkerState {
        self.state
    }

    /// Return the current pressure level.
    #[must_use]
    pub const fn pressure(&self) -> PressureLevel {
        self.pressure
    }

    /// Execute one bounded worker turn.
    pub fn step(&mut self, event: WorkerEvent) -> Result<StepOutcome, WorkerLoopError> {
        match event {
            WorkerEvent::Attach(request) => self.attach(request),
            other => {
                if self.state.is_terminal() {
                    return Err(WorkerLoopError::TerminalState);
                }
                if let Some(outcome) = self.expire_if_needed(other.now_ms())? {
                    return Ok(outcome);
                }
                match other {
                    WorkerEvent::Poll { now_ms } => self.poll(now_ms),
                    WorkerEvent::Notify(notification) => self.notify(notification),
                    WorkerEvent::Receipt(request) => self.receipt(request),
                    WorkerEvent::Attach(_) => unreachable!(),
                }
            }
        }
    }

    /// Execute at most `max_turns` events from `events`.
    pub fn run_bounded(&mut self, events: &[WorkerEvent], max_turns: usize) -> BoundedRun {
        let mut processed = 0usize;
        let mut emitted = 0usize;
        let mut error = None;
        for event in events.iter().take(max_turns) {
            match self.step(*event) {
                Ok(outcome) => {
                    processed = processed.saturating_add(1);
                    if outcome.output.is_some() {
                        emitted = emitted.saturating_add(1);
                    }
                    if self.state.is_terminal() {
                        break;
                    }
                }
                Err(err) => {
                    error = Some(err);
                    break;
                }
            }
        }
        BoundedRun {
            processed,
            emitted,
            terminal: self.state.is_terminal(),
            error,
        }
    }

    fn attach(&mut self, request: AttachRequest) -> Result<StepOutcome, WorkerLoopError> {
        match self.state {
            WorkerState::Detached => {}
            state if state.is_terminal() => return Err(WorkerLoopError::TerminalState),
            WorkerState::Attached => return Err(WorkerLoopError::AlreadyAttached),
            WorkerState::Revoked | WorkerState::Shutdown | WorkerState::LeaseExpired => {
                return Err(WorkerLoopError::TerminalState);
            }
        }
        if !request.endpoint.badge().matches_identity(self.identity) {
            return Err(WorkerLoopError::BadgeMismatch);
        }
        let lease = LeaseWindow::new(request.now_ms, request.lease_ttl_ms)?;
        self.endpoint = Some(request.endpoint);
        self.lease = Some(lease);
        self.state = WorkerState::Attached;
        if let WorkerMode::Heartbeat {
            ref mut next_due_ms,
            ..
        } = self.mode
        {
            *next_due_ms = request.now_ms;
        }
        let output = self.emit_lifecycle(request.now_ms, LifecycleEvent::Attached)?;
        Ok(StepOutcome {
            progress: WorkerProgress::Attached,
            output: Some(output),
        })
    }

    fn poll(&mut self, now_ms: u64) -> Result<StepOutcome, WorkerLoopError> {
        self.require_attached()?;
        match self.mode {
            WorkerMode::Heartbeat {
                interval_ms,
                ref mut next_due_ms,
                ref mut tick,
            } => {
                if now_ms < *next_due_ms {
                    return Ok(StepOutcome {
                        progress: WorkerProgress::Idle,
                        output: None,
                    });
                }
                let record = TelemetryRecord::Heartbeat {
                    now_ms,
                    tick: *tick,
                };
                *tick = tick.saturating_add(1);
                *next_due_ms = now_ms.saturating_add(interval_ms);
                let output = self.emit(InvocationKind::Telemetry(record))?;
                Ok(StepOutcome {
                    progress: WorkerProgress::Emitted,
                    output: Some(output),
                })
            }
            WorkerMode::Receipt { .. } => Ok(StepOutcome {
                progress: WorkerProgress::Idle,
                output: None,
            }),
        }
    }

    fn notify(&mut self, notification: WorkerNotification) -> Result<StepOutcome, WorkerLoopError> {
        self.require_attached()?;
        let now_ms = notification.now_ms();
        let event = match notification {
            WorkerNotification::Revoke { .. } => LifecycleEvent::Revoked,
            WorkerNotification::Shutdown { .. } => LifecycleEvent::Shutdown,
            WorkerNotification::Lease { ttl_ms, .. } => {
                self.lease = Some(LeaseWindow::new(now_ms, ttl_ms)?);
                LifecycleEvent::LeaseRenewed
            }
            WorkerNotification::Pressure { level, .. } => {
                self.pressure = level;
                LifecycleEvent::Pressure(level)
            }
        };
        let output = self.emit_lifecycle(now_ms, event)?;
        match event {
            LifecycleEvent::Revoked => self.finish_terminal(WorkerState::Revoked),
            LifecycleEvent::Shutdown => self.finish_terminal(WorkerState::Shutdown),
            _ => {}
        }
        Ok(StepOutcome {
            progress: if self.state.is_terminal() {
                WorkerProgress::Terminal
            } else {
                WorkerProgress::Lifecycle
            },
            output: Some(output),
        })
    }

    fn receipt(&mut self, request: ReceiptRequest) -> Result<StepOutcome, WorkerLoopError> {
        self.require_attached()?;
        let expected = self
            .mode
            .receipt_kind()
            .ok_or(WorkerLoopError::ReceiptMismatch)?;
        if request.kind != expected {
            return Err(WorkerLoopError::ReceiptMismatch);
        }
        let sequence = self.next_sequence();
        let record = ReceiptRecord {
            now_ms: request.now_ms,
            sequence,
            receipt_id: request.receipt_id,
            kind: request.kind,
        };
        let output = self.emit_with_sequence(sequence, InvocationKind::Receipt(record))?;
        Ok(StepOutcome {
            progress: WorkerProgress::Emitted,
            output: Some(output),
        })
    }

    fn expire_if_needed(&mut self, now_ms: u64) -> Result<Option<StepOutcome>, WorkerLoopError> {
        self.require_attached()?;
        let Some(lease) = self.lease else {
            return Err(WorkerLoopError::NotAttached);
        };
        if !lease.is_expired(now_ms) {
            return Ok(None);
        }
        let output = self.emit_lifecycle(now_ms, LifecycleEvent::LeaseExpired)?;
        self.finish_terminal(WorkerState::LeaseExpired);
        Ok(Some(StepOutcome {
            progress: WorkerProgress::Terminal,
            output: Some(output),
        }))
    }

    fn require_attached(&self) -> Result<(), WorkerLoopError> {
        match self.state {
            WorkerState::Attached => Ok(()),
            WorkerState::Detached => Err(WorkerLoopError::NotAttached),
            WorkerState::Revoked | WorkerState::Shutdown | WorkerState::LeaseExpired => {
                Err(WorkerLoopError::TerminalState)
            }
        }
    }

    fn emit_lifecycle(
        &mut self,
        now_ms: u64,
        event: LifecycleEvent,
    ) -> Result<EndpointInvocation, WorkerLoopError> {
        let sequence = self.next_sequence();
        let record = LifecycleRecord {
            now_ms,
            sequence,
            event,
        };
        self.emit_with_sequence(sequence, InvocationKind::Lifecycle(record))
    }

    fn emit(&mut self, kind: InvocationKind) -> Result<EndpointInvocation, WorkerLoopError> {
        let sequence = self.next_sequence();
        self.emit_with_sequence(sequence, kind)
    }

    fn emit_with_sequence(
        &self,
        sequence: u64,
        kind: InvocationKind,
    ) -> Result<EndpointInvocation, WorkerLoopError> {
        let endpoint = self.endpoint.ok_or(WorkerLoopError::NotAttached)?;
        Ok(EndpointInvocation {
            endpoint,
            badge: self.identity.badge_for(invocation_action(kind)),
            sequence,
            kind,
        })
    }

    fn next_sequence(&mut self) -> u64 {
        self.sequence = self.sequence.saturating_add(1);
        self.sequence
    }

    fn finish_terminal(&mut self, state: WorkerState) {
        self.state = state;
        self.endpoint = None;
        self.lease = None;
    }
}

fn invocation_action(kind: InvocationKind) -> WorkerEndpointAction {
    match kind {
        InvocationKind::Telemetry(_) => WorkerEndpointAction::Telemetry,
        InvocationKind::Receipt(_) => WorkerEndpointAction::Receipt,
        InvocationKind::Lifecycle(record) => match record.event {
            LifecycleEvent::Attached => WorkerEndpointAction::Attach,
            LifecycleEvent::LeaseRenewed | LifecycleEvent::LeaseExpired => {
                WorkerEndpointAction::Lease
            }
            LifecycleEvent::Revoked | LifecycleEvent::Shutdown => WorkerEndpointAction::Revoke,
            LifecycleEvent::Pressure(_) => WorkerEndpointAction::Telemetry,
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn heartbeat_identity() -> WorkerIdentity {
        WorkerIdentity::new(WorkerRole::Heartbeat, 7, 2, 3, 4)
    }

    fn attach_event(identity: WorkerIdentity, now_ms: u64, ttl_ms: u64) -> WorkerEvent {
        WorkerEvent::Attach(AttachRequest {
            endpoint: EndpointCap::new(11, identity.badge()).expect("valid endpoint"),
            now_ms,
            lease_ttl_ms: ttl_ms,
        })
    }

    #[test]
    fn attach_requires_matching_badge() {
        let identity = heartbeat_identity();
        let wrong = WorkerIdentity::new(WorkerRole::Heartbeat, 7, 3, 3, 4);
        let endpoint = EndpointCap::new(11, wrong.badge()).expect("valid endpoint");
        let mut loop_state =
            WorkerLoop::heartbeat(identity, DEFAULT_HEARTBEAT_INTERVAL_MS).expect("heartbeat loop");
        let err = loop_state
            .step(WorkerEvent::Attach(AttachRequest {
                endpoint,
                now_ms: 0,
                lease_ttl_ms: 10,
            }))
            .expect_err("badge mismatch");
        assert_eq!(err, WorkerLoopError::BadgeMismatch);
    }

    #[test]
    fn heartbeat_emits_bounded_telemetry_after_attach() {
        let identity = heartbeat_identity();
        let mut loop_state =
            WorkerLoop::heartbeat(identity, 5).expect("heartbeat loop should be valid");
        let attached = loop_state
            .step(attach_event(identity, 10, 50))
            .expect("attach should pass");
        assert_eq!(attached.progress, WorkerProgress::Attached);

        let first = loop_state
            .step(WorkerEvent::Poll { now_ms: 10 })
            .expect("poll should pass")
            .output
            .expect("heartbeat telemetry");
        assert_eq!(
            first.badge,
            identity.badge_for(WorkerEndpointAction::Telemetry)
        );
        assert!(matches!(
            first.kind,
            InvocationKind::Telemetry(TelemetryRecord::Heartbeat {
                now_ms: 10,
                tick: 0
            })
        ));

        let idle = loop_state
            .step(WorkerEvent::Poll { now_ms: 11 })
            .expect("early poll should be idle");
        assert_eq!(idle.progress, WorkerProgress::Idle);
        assert!(idle.output.is_none());
    }

    #[test]
    fn notification_revoke_blocks_late_telemetry() {
        let identity = heartbeat_identity();
        let mut loop_state =
            WorkerLoop::heartbeat(identity, 1).expect("heartbeat loop should be valid");
        loop_state
            .step(attach_event(identity, 0, 20))
            .expect("attach should pass");
        let revoked = loop_state
            .step(WorkerEvent::Notify(WorkerNotification::Revoke {
                now_ms: 1,
            }))
            .expect("revoke should emit lifecycle");
        assert_eq!(revoked.progress, WorkerProgress::Terminal);
        assert_eq!(loop_state.state(), WorkerState::Revoked);
        let err = loop_state
            .step(WorkerEvent::Poll { now_ms: 2 })
            .expect_err("late telemetry should be refused");
        assert_eq!(err, WorkerLoopError::TerminalState);
    }

    #[test]
    fn lease_expiry_is_emitted_before_new_work() {
        let identity = heartbeat_identity();
        let mut loop_state =
            WorkerLoop::heartbeat(identity, 1).expect("heartbeat loop should be valid");
        loop_state
            .step(attach_event(identity, 0, 5))
            .expect("attach should pass");
        let expired = loop_state
            .step(WorkerEvent::Poll { now_ms: 5 })
            .expect("expiry should emit lifecycle");
        assert_eq!(expired.progress, WorkerProgress::Terminal);
        assert!(matches!(
            expired.output.expect("expiry output").kind,
            InvocationKind::Lifecycle(LifecycleRecord {
                event: LifecycleEvent::LeaseExpired,
                ..
            })
        ));
        assert_eq!(loop_state.state(), WorkerState::LeaseExpired);
    }

    #[test]
    fn run_bounded_respects_turn_budget() {
        let identity = heartbeat_identity();
        let mut loop_state =
            WorkerLoop::heartbeat(identity, 1).expect("heartbeat loop should be valid");
        let events = [
            attach_event(identity, 0, 10),
            WorkerEvent::Poll { now_ms: 0 },
            WorkerEvent::Poll { now_ms: 1 },
        ];
        let run = loop_state.run_bounded(&events, 2);
        assert_eq!(run.processed, 2);
        assert_eq!(run.emitted, 2);
        assert!(!run.terminal);
        assert_eq!(run.error, None);
    }

    #[test]
    fn gpu_and_lora_receipt_modes_emit_only_matching_receipts() {
        let identity = WorkerIdentity::new(WorkerRole::Gpu, 1, 1, 1, 1);
        let mut loop_state = WorkerLoop::gpu_receipts(identity).expect("gpu receipt loop");
        loop_state
            .step(attach_event(identity, 0, 10))
            .expect("attach should pass");
        let receipt = loop_state
            .step(WorkerEvent::Receipt(ReceiptRequest {
                now_ms: 1,
                receipt_id: 99,
                kind: ReceiptKind::GpuControl,
            }))
            .expect("gpu receipt")
            .output
            .expect("receipt output");
        assert!(matches!(
            receipt.kind,
            InvocationKind::Receipt(ReceiptRecord {
                receipt_id: 99,
                kind: ReceiptKind::GpuControl,
                ..
            })
        ));
        assert_eq!(
            receipt.badge,
            identity.badge_for(WorkerEndpointAction::Receipt)
        );
        let err = loop_state
            .step(WorkerEvent::Receipt(ReceiptRequest {
                now_ms: 2,
                receipt_id: 100,
                kind: ReceiptKind::LoraControl,
            }))
            .expect_err("wrong receipt kind");
        assert_eq!(err, WorkerLoopError::ReceiptMismatch);
    }
}
