.\" CLASSIFICATION: COMMUNITY
.\" Filename: cohesix.1 v0.1
.\" Author: Lukas Bower
.\" Date Modified: 2025-06-29
.TH COHESIX 1 "2025-06-29" "Cohesix" "User Commands"
.SH NAME
cohesix \- symlink to cohcli, primary CLI dispatcher for Cohesix
.SH SYNOPSIS
.B cohesix
.RI [options]
.SH DESCRIPTION
Invokes the primary CLI interface for Cohesix. Accepts all cohcli arguments such as
.B --help,
.B --version,
and subcommands like
.BR trace ,
.BR role ,
.BR build .
.SH OPTIONS
All options are passed directly to cohcli. See \fBcohcli(1)\fR.
