.\" CLASSIFICATION: COMMUNITY
.\" Filename: cohesix-shell.1 v0.1
.\" Author: Lukas Bower
.\" Date Modified: 2025-06-29
.TH COHESIX-SHELL 1 "2025-06-29" "Cohesix" "User Commands"
.SH NAME
cohesix-shell \- invokes a BusyBox-compatible interactive shell within the Cohesix environment
.SH SYNOPSIS
.B cohesix-shell
.SH DESCRIPTION
Starts a BusyBox-compatible interactive shell in the Cohesix environment.
It accepts no arguments and simply launches a shell.
