.\" CLASSIFICATION: COMMUNITY
.\" Filename: cohtrace.1 v0.2
.\" Author: Lukas Bower
.\" Date Modified: 2025-07-15
.TH COHTRACE 1 "2025-07-15" "Cohesix v1.0" "Cohesix Project"
.SH NAME
cohtrace \- trace inspection utilities
.SH SYNOPSIS
.B cohtrace
.RI [command] " [options]"
.SH DESCRIPTION
Inspect and manipulate worker traces for debugging and federation.
.SH OPTIONS
.TP
.B --force
Overwrite existing trace data. \fBUse with care.\fR
.SH EXIT STATUS
.TP
.B 0
Success.
.TP
.B 1
Invalid trace file.
.TP
.B 2
Connection failure.
.SH FILES

.SH EXAMPLES
.P
cohtrace pull worker01 > log.json
.SH SEE ALSO

