.\" CLASSIFICATION: COMMUNITY
.\" Filename: cut.1 v0.1
.\" Author: Lukas Bower
.\" Date Modified: 2025-07-12
.TH CUT 1 "2025-07-12" "Cohesix v1.0" "Cohesix Project"
.SH NAME
cut \- remove sections from lines
.SH SYNOPSIS
.B cut
.SH DESCRIPTION
cut is provided by BusyBox. Use "cut --help" for options.
.SH OPTIONS
See \fB--help\fR for available options.
.SH FILES

.SH EXAMPLES

.SH SEE ALSO

