.\" CLASSIFICATION: COMMUNITY
.\" Filename: ip.8 v0.1
.\" Author: Lukas Bower
.\" Date Modified: 2025-07-12
.TH IP 8 "2025-07-12" "Cohesix v1.0" "Cohesix Project"
.SH NAME
ip \- show / manipulate routing and devices
.SH SYNOPSIS
.B ip
.SH DESCRIPTION
ip is provided by BusyBox. Use "ip --help" for options.
.SH OPTIONS
See \fB--help\fR for available options.
.SH FILES

.SH EXAMPLES

.SH SEE ALSO

