.\" CLASSIFICATION: COMMUNITY
.\" Filename: mkdir.1 v0.1
.\" Author: Lukas Bower
.\" Date Modified: 2025-07-12
.TH MKDIR 1 "2025-07-12" "Cohesix v1.0" "Cohesix Project"
.SH NAME
mkdir \- create directories
.SH SYNOPSIS
.B mkdir
.SH DESCRIPTION
mkdir is provided by BusyBox. Use "mkdir --help" for options.
.SH OPTIONS
See \fB--help\fR for available options.
.SH FILES

.SH EXAMPLES

.SH SEE ALSO

