.\" CLASSIFICATION: COMMUNITY
.\" Filename: mount.8 v0.1
.\" Author: Lukas Bower
.\" Date Modified: 2025-07-12
.TH MOUNT 8 "2025-07-12" "Cohesix v1.0" "Cohesix Project"
.SH NAME
mount \- mount filesystems
.SH SYNOPSIS
.B mount
.SH DESCRIPTION
mount is provided by BusyBox. Use "mount --help" for options.
.SH OPTIONS
See \fB--help\fR for available options.
.SH FILES

.SH EXAMPLES

.SH SEE ALSO

