#pragma once

/* disabled: CONFIG_LIB_PLAT_SUPPORT_SERIAL_PORT_X86_COM1 */
/* disabled: CONFIG_LIB_PLAT_SUPPORT_SERIAL_PORT_X86_COM2 */
/* disabled: CONFIG_LIB_PLAT_SUPPORT_SERIAL_PORT_X86_COM3 */
/* disabled: CONFIG_LIB_PLAT_SUPPORT_SERIAL_PORT_X86_COM4 */
/* disabled: CONFIG_LIB_PLAT_SUPPORT_SERIAL_TEXT_EGA */
/* disabled: CONFIG_LIB_PLAT_SUPPORT_LPTMR_CLOCK_32kHZ */
/* disabled: CONFIG_LIB_PLAT_SUPPORT_LPTMR_CLOCK_24MHz */
/* disabled: CONFIG_LIB_PLAT_SUPPORT_HAVE_TIMER */
