# Author: Lukas Bower
# Purpose: Define the cfg-aware Rust source risk-ratchet audit tool.
# Copyright 2026 Lukas Bower

[package]
name = "rust-risk-audit"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
proc-macro2 = "1.0.107"
serde = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
syn = { version = "3.0.3", features = ["full", "visit"] }
toml = "1.1.4"
