#!/usr/bin/env bash
# Author: Lukas Bower
# Purpose: Extract and render tracked Markdown Mermaid blocks for 26c audit evidence.
# Copyright 2026 Lukas Bower

set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: scripts/ci/render_mermaid_github.sh --markdown-list <path> --out <dir>

Extracts Mermaid blocks from tracked Markdown into <dir>/sources. If the
Mermaid CLI (`mmdc`) is installed, renders SVG files into <dir>/rendered.
USAGE
}

markdown_list=""
out_dir=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --markdown-list)
      shift
      [[ $# -gt 0 ]] || {
        echo "--markdown-list requires a value" >&2
        exit 2
      }
      markdown_list="$1"
      ;;
    --out)
      shift
      [[ $# -gt 0 ]] || {
        echo "--out requires a value" >&2
        exit 2
      }
      out_dir="$1"
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
  shift
done

[[ -n "${markdown_list}" && -n "${out_dir}" ]] || {
  usage >&2
  exit 2
}

repo_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
mkdir -p "${out_dir}"

python3 - "$repo_root" "$markdown_list" "$out_dir" <<'PY'
import csv
import pathlib
import re
import sys

root = pathlib.Path(sys.argv[1])
markdown_list = pathlib.Path(sys.argv[2])
out_dir = pathlib.Path(sys.argv[3])
sources = out_dir / "sources"
sources.mkdir(parents=True, exist_ok=True)

fence_re = re.compile(r"^\s*```\s*mermaid\s*$", re.I)
end_re = re.compile(r"^\s*```\s*$")
manifest = out_dir / "render_manifest.csv"
rows = []

def safe_name(rel: str, index: int) -> str:
    stem = re.sub(r"[^A-Za-z0-9_.-]+", "_", rel)
    return f"{stem}__block_{index:03d}.mmd"

for rel in markdown_list.read_text(encoding="utf-8").splitlines():
    rel = rel.strip()
    if not rel:
        continue
    path = root / rel
    lines = path.read_text(encoding="utf-8").splitlines()
    in_block = False
    start = 0
    body = []
    block_index = 0
    for line_no, line in enumerate(lines, start=1):
        if not in_block:
            if fence_re.match(line):
                in_block = True
                start = line_no
                body = []
            continue
        if end_re.match(line):
            block_index += 1
            name = safe_name(rel, block_index)
            source_path = sources / name
            source_path.write_text("\n".join(body) + "\n", encoding="utf-8")
            rows.append([rel, str(block_index), str(start), str(line_no), str(source_path)])
            in_block = False
            continue
        body.append(line)
    if in_block:
        raise SystemExit(f"unterminated Mermaid fence in {rel}:{start}")

with manifest.open("w", encoding="utf-8", newline="") as handle:
    handle.write("# Author: Lukas Bower\n")
    handle.write("# Purpose: Map Mermaid source extracts to tracked Markdown locations.\n")
    handle.write("# Copyright 2026 Lukas Bower\n")
    writer = csv.writer(handle)
    writer.writerow(["path", "block_index", "line_start", "line_end", "source_path"])
    writer.writerows(rows)

print(f"extracted {len(rows)} Mermaid block(s) to {sources}")
PY

readme="${out_dir}/README.md"
{
  echo "<!-- Author: Lukas Bower -->"
  echo "<!-- Purpose: Record Mermaid render evidence generated by scripts/ci/render_mermaid_github.sh. -->"
  echo "<!-- Copyright 2026 Lukas Bower -->"
  echo
  echo "# Mermaid Render Evidence"
  echo
  echo "- markdown_list: ${markdown_list}"
  echo "- source_dir: ${out_dir}/sources"
  echo "- manifest: ${out_dir}/render_manifest.csv"
} >"${readme}"

if command -v mmdc >/dev/null 2>&1; then
  mkdir -p "${out_dir}/rendered"
  rendered=0
  while IFS= read -r source; do
    name=$(basename "${source}" .mmd)
    mmdc -i "${source}" -o "${out_dir}/rendered/${name}.svg" >/dev/null
    rendered=$((rendered + 1))
  done < <(find "${out_dir}/sources" -type f -name '*.mmd' | sort)
  {
    echo "- renderer: mmdc"
    echo "- rendered_svg_count: ${rendered}"
  } >>"${readme}"
else
  {
    echo "- renderer: unavailable"
    echo "- rendered_svg_count: 0"
    echo
    echo "The Mermaid CLI was not found on PATH. Sources were extracted for review; install mmdc and rerun this script for SVG render artifacts."
  } >>"${readme}"
fi

echo "mermaid render evidence written to ${out_dir}"
