# Author: Lukas Bower
# Purpose: Configure the seL4 syscall bindings crate and build-time header inputs.
# Copyright 2026 Lukas Bower
[package]
name = "sel4-sys"
version = "0.0.28"
edition = "2021"
publish = false
build = "build.rs"

[features]
default = []

[dependencies]
log = { version = "0.4.33", default-features = false }

[build-dependencies]
bindgen = { version = "0.72.1", default-features = false, features = ["runtime"] }
cargo-build-directive = { workspace = true }
