// Author: Lukas Bower
// Purpose: Resolve compiler-owned host provider and surface contracts without accepting client-selected authority or evidence modes.
// Copyright 2026 Lukas Bower
// SPDX-License-Identifier: Apache-2.0
#![forbid(unsafe_code)]

use alloc::string::String;
use core::fmt;
use serde_json::Value;
use std::sync::OnceLock;

static REGISTRY: OnceLock<Result<Value, ProviderError>> = OnceLock::new();

/// Deterministic refusal classes shared by every Rust provider consumer.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProviderError {
    NotRegistered,
    InvalidTarget,
    RequestLimit,
    InvalidRegistry,
}

impl fmt::Display for ProviderError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::NotRegistered => "not_registered provider",
            Self::InvalidTarget => "invalid_target provider",
            Self::RequestLimit => "request_limit provider",
            Self::InvalidRegistry => "invalid_registry provider",
        })
    }
}
impl std::error::Error for ProviderError {}

/// Exact generated bytes; reading the registry cannot promote implementation state.
pub fn registry_json() -> &'static str {
    crate::provider_generated::REGISTRY_JSON
}

/// Immutable cached projection of the compiler-owned integration graph extension.
pub fn registry() -> Result<&'static Value, ProviderError> {
    match REGISTRY.get_or_init(|| {
        serde_json::from_str(registry_json()).map_err(|_| ProviderError::InvalidRegistry)
    }) {
        Ok(value) => Ok(value),
        Err(error) => Err(*error),
    }
}

/// Resolve a known action without replacing the ticket-agent admission checks.
pub fn action(id: &str) -> Result<&'static Value, ProviderError> {
    let families = registry()?["contract"]["families"]
        .as_array()
        .ok_or(ProviderError::InvalidRegistry)?;
    for family in families {
        for action in family["actions"]
            .as_array()
            .ok_or(ProviderError::InvalidRegistry)?
        {
            if action["id"] == id {
                return Ok(action);
            }
        }
    }
    Err(ProviderError::NotRegistered)
}

/// Resolve a public surface while preserving its stable integration identity.
pub fn surface(id: &str) -> Result<&'static Value, ProviderError> {
    registry()?["contract"]["integration_surfaces"]
        .as_array()
        .ok_or(ProviderError::InvalidRegistry)?
        .iter()
        .find(|surface| surface["id"] == id)
        .ok_or(ProviderError::NotRegistered)
}

/// Enforce the compiler's action wire bound before executor dispatch.
pub fn validate_request_size(id: &str, bytes: usize) -> Result<(), ProviderError> {
    let bound = action(id)?["maximum_request_bytes"]
        .as_u64()
        .ok_or(ProviderError::InvalidRegistry)?;
    if bytes as u64 > bound {
        return Err(ProviderError::RequestLimit);
    }
    Ok(())
}

/// Apply the generated target grammar; callers cannot supply shell or host paths.
pub fn validate_target(id: &str, target: Option<&str>) -> Result<(), ProviderError> {
    let grammar = action(id)?["target_grammar"]
        .as_str()
        .ok_or(ProviderError::InvalidRegistry)?;
    if grammar == "none" {
        return if target.is_none() {
            Ok(())
        } else {
            Err(ProviderError::InvalidTarget)
        };
    }
    let target = target.ok_or(ProviderError::InvalidTarget)?;
    let valid = match grammar {
        "cas_sha256" => {
            target.len() == 64
                && target
                    .bytes()
                    .all(|b| b.is_ascii_digit() || (b'a'..=b'f').contains(&b))
        }
        "native_id" | "physical_device" => {
            target
                .as_bytes()
                .first()
                .is_some_and(u8::is_ascii_alphanumeric)
                && crate::validate_id(target).is_ok()
        }
        _ => return Err(ProviderError::InvalidRegistry),
    };
    if valid {
        Ok(())
    } else {
        Err(ProviderError::InvalidTarget)
    }
}

/// Resolve every canonical read by the longest compiler-owned component prefix.
pub fn read_visibility(path: &str) -> Result<(&'static str, &'static str), ProviderError> {
    if path != "/"
        && (!path.starts_with('/')
            || path.len() > 255
            || path
                .split('/')
                .skip(1)
                .any(|part| part == "." || crate::validate_id(part).is_err()))
    {
        return Err(ProviderError::InvalidTarget);
    }
    let rules = registry()?["contract"]["read_visibility"]
        .as_array()
        .ok_or(ProviderError::InvalidRegistry)?;
    let rule = rules
        .iter()
        .filter(|rule| {
            rule["prefix"].as_str().is_some_and(|prefix| {
                prefix == "/"
                    || path == prefix
                    || path
                        .strip_prefix(prefix)
                        .is_some_and(|rest| rest.starts_with('/'))
            })
        })
        .max_by_key(|rule| rule["prefix"].as_str().map_or(0, str::len))
        .ok_or(ProviderError::InvalidRegistry)?;
    Ok((
        rule["class"]
            .as_str()
            .ok_or(ProviderError::InvalidRegistry)?,
        rule["owner_binding"]
            .as_str()
            .ok_or(ProviderError::InvalidRegistry)?,
    ))
}

/// Render one bounded human-readable action list from the registry.
pub fn action_names() -> Result<alloc::vec::Vec<String>, ProviderError> {
    let mut names = alloc::vec::Vec::new();
    for family in registry()?["contract"]["families"]
        .as_array()
        .ok_or(ProviderError::InvalidRegistry)?
    {
        for action in family["actions"]
            .as_array()
            .ok_or(ProviderError::InvalidRegistry)?
        {
            names.push(
                action["id"]
                    .as_str()
                    .ok_or(ProviderError::InvalidRegistry)?
                    .into(),
            );
        }
    }
    Ok(names)
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn shared_generated_registry_enforces_targets_bounds_and_stable_surface_links() {
        assert_eq!(
            surface("rest").unwrap()["integration_id"],
            "rest-gateway-projection"
        );
        assert!(validate_target("systemd.restart", Some("cohesix.service")).is_ok());
        for target in [
            "/etc/service",
            "../service",
            "--system",
            "a..b",
            "unit\nservice",
        ] {
            assert_eq!(
                validate_target("systemd.restart", Some(target)),
                Err(ProviderError::InvalidTarget)
            );
        }
        assert_eq!(
            validate_request_size("systemd.restart", 2049),
            Err(ProviderError::RequestLimit)
        );
        assert_eq!(action("shell.execute"), Err(ProviderError::NotRegistered));
    }
}
