/*
 * Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
 *
 * SPDX-License-Identifier: GPL-2.0-only
 */

/*
 * This file is autogenerated by kernel/tools/hardware_gen.py
 */

#pragma once

#include <types.h>

#define MAX_NUM_REGIONS 1

struct elfloader_driver;

struct elfloader_device {
    const char *compat;
    volatile void *region_bases[MAX_NUM_REGIONS];
    struct elfloader_driver *drv;
};

struct elfloader_cpu {
    const char *compat;
    const char *enable_method;
    word_t cpu_id;
    word_t extra_data;
};

#ifdef DRIVER_COMMON
struct elfloader_device elfloader_devices[] = {
    {
        /* /timer */
        .compat = "arm,armv8-timer",
        .region_bases = {
            (void *)0,
        },
    },
    {
        /* /soc/serial@7e215040 */
        .compat = "brcm,bcm2835-aux-uart",
        .region_bases = {
            (void *)0xfe215040,
        },
    },
    {
        /* /soc/firmware */
        .compat = "raspberrypi,bcm2835-firmware",
        .region_bases = {
            (void *)0,
        },
    },
};

struct elfloader_cpu elfloader_cpus[] = {
    {
        /* /cpus/cpu@0 */
        .compat = "arm,cortex-a72",
        .enable_method = "spin-table",
        .cpu_id = 0x0,
        .extra_data = 0xd8
    },
    {
        /* /cpus/cpu@1 */
        .compat = "arm,cortex-a72",
        .enable_method = "spin-table",
        .cpu_id = 0x1,
        .extra_data = 0xe0
    },
    {
        /* /cpus/cpu@2 */
        .compat = "arm,cortex-a72",
        .enable_method = "spin-table",
        .cpu_id = 0x2,
        .extra_data = 0xe8
    },
    {
        /* /cpus/cpu@3 */
        .compat = "arm,cortex-a72",
        .enable_method = "spin-table",
        .cpu_id = 0x3,
        .extra_data = 0xf0
    },
    { .compat = NULL /* sentinel */ },
};
#else
extern struct elfloader_device elfloader_devices[];
extern struct elfloader_cpu elfloader_cpus[];
#endif