/* generated by /Users/lukasbower/seL4_16/tools/seL4/cmake-tool/helpers/platform_sift.py BEGIN */
int num_memory_regions = 2;

struct memory_region {
    size_t start;
    size_t end;
} memory_region[2] = {
	{ .start = 4096, .end = 994050048 },
	{ .start = 1073741824, .end = 2147483648 },
};
/* generated by /Users/lukasbower/seL4_16/tools/seL4/cmake-tool/helpers/platform_sift.py END */
