export const buildHiveStyle = (tokens) => {
  const flowBlobRadius = Math.max(6, tokens.sizes.flow * 6);
  const flowBlobSpacing = Math.max(8, flowBlobRadius * 1.6);
  const agentLabelSize = Math.max(10, tokens.sizes.agent + 1);
  const agentLabelOffset = Math.max(8, tokens.sizes.agent + 4);
  return {
    agentRadius: tokens.sizes.agent,
    glowRadius: tokens.sizes.glow,
    pollenRadius: tokens.sizes.pollen,
    pulseRadius: tokens.sizes.pulse,
    flowBlobRadius,
    flowBlobSpacing,
    driftAmplitude: tokens.sizes.drift,
    pollenLife: tokens.motion.pollenLife,
    pulseLife: tokens.motion.pulseLife,
    heatDecay: tokens.motion.heatDecay,
    flowDecay: tokens.motion.flowDecay,
    pollenSpeedBase: 120,
    pollenSpeedScale: 80,
    driftRateX: 0.35,
    driftRateY: 0.28,
    maxPollen: 240,
    maxPulses: 80,
    positionScale: 0.8,
    errorDecay: 1.4,
    flowIntensityMax: 6,
    flowIntensityError: 1.4,
    flowInactiveThreshold: 0.05,
    flowDetailThreshold: 0.3,
    flowBlobAlphaMin: 0.08,
    flowBlobAlphaRange: 0.32,
    flowBlobScaleMin: 0.55,
    flowBlobScaleRange: 0.85,
    flowBlobInnerAlpha: 0.7,
    flowBlobLimit: 64,
    clusterRadiusBase: 26,
    clusterRadiusStep: 6,
    clusterRadiusMin: 28,
    clusterRadiusMax: 120,
    clusterAlpha: 0.16,
    clusterAlphaCollapsed: 0.24,
    clusterLabelOffset: 10,
    clusterLabelSize: 12,
    agentLabelSize,
    agentLabelOffset,
    agentScaleBase: 0.7,
    agentScaleHeat: 0.6,
    glowScaleBase: 0.6,
    glowScaleHeat: 0.8,
    glowAlphaMin: 0.1,
    glowAlphaMax: 0.9,
    glowErrorBoost: 0.5,
    errorTintThreshold: 0.1,
    errorGlowThreshold: 0.2,
    pulseScaleBase: 0.3,
    pulseScaleRange: 1.0,
    zoomMin: 0.45,
    zoomMax: 2.4,
    labelFont: tokens.fonts.ui,
  };
};
