.\" CLASSIFICATION: COMMUNITY
.\" Filename: cohagent.1 v0.1
.\" Author: Lukas Bower
.\" Date Modified: 2025-07-12
.TH COHAGENT 1 "2025-07-12" "Cohesix v1.0" "Cohesix Project"
.SH NAME
cohagent \- agent control utility
.SH SYNOPSIS
.B cohagent
.SH DESCRIPTION
Agent management CLI for starting, pausing, or migrating agents.
.SH OPTIONS
See \fB--help\fR for available options.
.SH FILES

.SH EXAMPLES

.SH SEE ALSO

