.\" CLASSIFICATION: COMMUNITY
.\" Filename: cohcli.1 v0.2
.\" Author: Lukas Bower
.\" Date Modified: 2025-07-14
.TH COHCLI 1
.SH NAME
cohcli \- Cohesix command line interface
.SH SYNOPSIS
.B cohcli
.RI [command] " [options]"
.SH DESCRIPTION
Command-line interface for interacting with Cohesix services and workers.
.SH OPTIONS
.B --version
Display version information and exit.
See \fB--help\fR for available subcommands.
.SH FILES

.SH EXAMPLES

.SH SEE ALSO
