.\" CLASSIFICATION: COMMUNITY
.\" Filename: cohcli.1 v0.1
.\" Author: Lukas Bower
.\" Date Modified: 2025-07-12
.TH COHCLI 1 "2025-07-12" "Cohesix v1.0" "Cohesix Project"
.SH NAME
cohcli \- interact with Cohesix
.SH SYNOPSIS
.B cohcli
.SH DESCRIPTION
Command-line interface for interacting with Cohesix services and workers.
.SH OPTIONS
See \fB--help\fR for available options.
.SH FILES

.SH EXAMPLES

.SH SEE ALSO

