.\" CLASSIFICATION: COMMUNITY
.\" Filename: cohcap.1 v0.1
.\" Author: Lukas Bower
.\" Date Modified: 2025-07-12
.TH COHCAP 1 "2025-07-12" "Cohesix v1.0" "Cohesix Project"
.SH NAME
cohcap \- manage demo capabilities
.SH SYNOPSIS
.B cohcap
.SH DESCRIPTION
Placeholder capability management CLI used for demos.
.SH OPTIONS
See \fB--help\fR for available options.
.SH FILES

.SH EXAMPLES

.SH SEE ALSO

