.\" CLASSIFICATION: COMMUNITY
.\" Filename: cohcc.1 v0.1
.\" Author: Lukas Bower
.\" Date Modified: 2025-07-12
.TH COHCC 1 "2025-07-12" "Cohesix v1.0" "Cohesix Project"
.SH NAME
cohcc \- compile Cohesix IR modules
.SH SYNOPSIS
.B cohcc
.SH DESCRIPTION
Cohesix compiler front-end for Cohesix IR modules.
.SH OPTIONS
See \fB--help\fR for available options.
.SH FILES

.SH EXAMPLES

.SH SEE ALSO

