.\" CLASSIFICATION: COMMUNITY
.\" Filename: cohrun.1 v0.1
.\" Author: Lukas Bower
.\" Date Modified: 2025-07-12
.TH COHRUN 1
.SH NAME
cohrun \- execute Cohesix binaries
.SH SYNOPSIS
cohrun <binary>
.SH DESCRIPTION
Wrapper to run built Cohesix binaries.
.TH COHRUN 1 "2025-07-12" "Cohesix v1.0" "Cohesix Project"
.SH NAME
cohrun \- run Cohesix demo scenarios
.SH SYNOPSIS
.B cohrun
.SH DESCRIPTION
Utility for running Cohesix demo scenarios and orchestrator actions.
.SH OPTIONS
See \fB--help\fR for available options.
.SH FILES

.SH EXAMPLES

.SH SEE ALSO

