.\" CLASSIFICATION: COMMUNITY
.\" Filename: cohrole.1 v0.1
.\" Author: Lukas Bower
.\" Date Modified: 2025-07-12
.TH COHROLE 1 "2025-07-12" "Cohesix v1.0" "Cohesix Project"
.SH NAME
cohrole \- display current role
.SH SYNOPSIS
.B cohrole
.SH DESCRIPTION
Display the current Cohesix runtime role.
.SH OPTIONS
See \fB--help\fR for available options.
.SH FILES

.SH EXAMPLES

.SH SEE ALSO

