.\" CLASSIFICATION: COMMUNITY
.\" Filename: cohtrace.1 v0.1
.\" Author: Lukas Bower
.\" Date Modified: 2025-07-12
.TH COHTRACE 1 "2025-07-12" "Cohesix v1.0" "Cohesix Project"
.SH NAME
cohtrace \- trace inspection utilities
.SH SYNOPSIS
.B cohtrace
.SH DESCRIPTION
Trace inspection and federation utilities.
.SH OPTIONS
See \fB--help\fR for available options.
.SH FILES

.SH EXAMPLES

.SH SEE ALSO

