.\" CLASSIFICATION: COMMUNITY
.\" Filename: head.1 v0.1
.\" Author: Lukas Bower
.\" Date Modified: 2025-07-12
.TH HEAD 1 "2025-07-12" "Cohesix v1.0" "Cohesix Project"
.SH NAME
head \- show the first lines of a file
.SH SYNOPSIS
.B head
.SH DESCRIPTION
head is provided by BusyBox. Use "head --help" for options.
.SH OPTIONS
See \fB--help\fR for available options.
.SH FILES

.SH EXAMPLES

.SH SEE ALSO

