.TH "ls" 1
.SH NAME
ls
.SH SYNOPSIS
ls [OPTIONS]
.SH DESCRIPTION
Usage: ls [OPTION]\.\.\. [FILE]\.\.\.
List information about the FILEs (the current directory by default)\.
Sort entries alphabetically if none of -cftuvSUX nor --sort is specified\.

Mandatory arguments to long options are mandatory for short options too\.
  -a, --all                  do not ignore entries starting with \.
  -A, --almost-all           do not list implied \. and \.\.
      --author               with -l, print the author of each file
  -b, --escape               print C-style escapes for nongraphic characters
      --block-size=SIZE      with -l, scale sizes by SIZE when printing them;
                             e\.g\., '--block-size=M'; see SIZE format below

  -B, --ignore-backups       do not list implied entries ending with ~
  -c                         with -lt: sort by, and show, ctime (time of last
                             change of file status information);
                             with -l: show ctime and sort by name;
                             otherwise: sort by ctime, newest first

  -C                         list entries by columns
      --color[=WHEN]         color the output WHEN; more info below
