
.TH "ps" 1
.SH NAME
ps
.SH SYNOPSIS
ps [OPTIONS]
.SH DESCRIPTION

Usage:
 ps [options]

 Try 'ps --help <simple|list|output|threads|misc|all>'
  or 'ps --help <s|l|o|t|m|a>'
 for additional help text\.

For more details see ps(1)\.

.\" CLASSIFICATION: COMMUNITY
.\" Filename: ps.1 v0.1
.\" Author: Lukas Bower
.\" Date Modified: 2025-07-12
.TH PS 1 "2025-07-12" "Cohesix v1.0" "Cohesix Project"
.SH NAME
ps \- process status
.SH SYNOPSIS
.B ps
.SH DESCRIPTION
ps is provided by BusyBox. Use "ps --help" for options.
.SH OPTIONS
See \fB--help\fR for available options.
.SH FILES

.SH EXAMPLES

.SH SEE ALSO

