.\" CLASSIFICATION: COMMUNITY
.\" Filename: scp.1 v0.1
.\" Author: Lukas Bower
.\" Date Modified: 2025-07-12
.TH SCP 1 "2025-07-12" "Cohesix v1.0" "Cohesix Project"
.SH NAME
scp \- secure copy (remote file copy program)
.SH SYNOPSIS
.B scp
.SH DESCRIPTION
scp is provided by BusyBox. Use "scp --help" for options.
.SH OPTIONS
See \fB--help\fR for available options.
.SH FILES

.SH EXAMPLES

.SH SEE ALSO

