.\" CLASSIFICATION: COMMUNITY
.\" Filename: sed.1 v0.1
.\" Author: Lukas Bower
.\" Date Modified: 2025-07-12
.TH SED 1 "2025-07-12" "Cohesix v1.0" "Cohesix Project"
.SH NAME
sed \- stream editor
.SH SYNOPSIS
.B sed
.SH DESCRIPTION
sed is provided by BusyBox. Use "sed --help" for options.
.SH OPTIONS
See \fB--help\fR for available options.
.SH FILES

.SH EXAMPLES

.SH SEE ALSO

