.\" CLASSIFICATION: COMMUNITY
.\" Filename: top.1 v0.1
.\" Author: Lukas Bower
.\" Date Modified: 2025-07-12
.TH TOP 1 "2025-07-12" "Cohesix v1.0" "Cohesix Project"
.SH NAME
top \- display running processes
.SH SYNOPSIS
.B top
.SH DESCRIPTION
top is provided by BusyBox. Use "top --help" for options.
.SH OPTIONS
See \fB--help\fR for available options.
.SH FILES

.SH EXAMPLES

.SH SEE ALSO

