// Copyright © 2025 Lukas Bower
// SPDX-License-Identifier: Apache-2.0
// Purpose: Emit manifest-derived Cohesix Python client defaults.
// Author: Lukas Bower

use crate::codegen::hash_bytes;
use crate::ir::{Manifest, TelemetryIngestEvictionPolicy};
use anyhow::{Context, Result};
use cohsh_core::{MAX_ECHO_LEN, MAX_ID_LEN, MAX_JSON_LEN, MAX_LINE_LEN, MAX_PATH_LEN, MAX_TICKET_LEN};
use std::fmt::Write as _;
use std::fs;
use std::path::Path;

/// Maximum bytes allowed for a telemetry push record.
pub const TELEMETRY_RECORD_MAX_BYTES: usize = 4096;
/// Telemetry push schema label.
pub const TELEMETRY_PUSH_SCHEMA: &str = "cohsh-telemetry-push/v1";

/// Rendered Cohesix Python defaults plus the hash of the output.
#[derive(Debug, Clone)]
pub struct CohesixPyDefaults {
    pub python: String,
    pub hash: String,
}

/// Render the Python defaults module contents.
pub fn render_defaults(manifest: &Manifest, manifest_hash: &str) -> CohesixPyDefaults {
    let mut contents = String::new();
    writeln!(
        contents,
        "# Generated by coh-rtc. DO NOT EDIT BY HAND."
    )
    .ok();
    writeln!(contents, "# Author: Lukas Bower").ok();
    writeln!(
        contents,
        "# Purpose: Provide manifest-derived defaults for the Cohesix Python client."
    )
    .ok();
    writeln!(contents).ok();
    writeln!(contents, "DEFAULTS = {{").ok();
    writeln!(
        contents,
        "    \"manifest_sha256\": \"{}\",",
        manifest_hash
    )
    .ok();
    writeln!(
        contents,
        "    \"secure9p\": {{\"msize\": {}, \"walk_depth\": {}}},",
        manifest.secure9p.msize, manifest.secure9p.walk_depth
    )
    .ok();
    writeln!(contents, "    \"console\": {{").ok();
    writeln!(
        contents,
        "        \"max_line_len\": {},",
        MAX_LINE_LEN
    )
    .ok();
    writeln!(
        contents,
        "        \"max_path_len\": {},",
        MAX_PATH_LEN
    )
    .ok();
    writeln!(
        contents,
        "        \"max_json_len\": {},",
        MAX_JSON_LEN
    )
    .ok();
    writeln!(contents, "        \"max_id_len\": {},", MAX_ID_LEN).ok();
    writeln!(
        contents,
        "        \"max_echo_len\": {},",
        MAX_ECHO_LEN
    )
    .ok();
    writeln!(
        contents,
        "        \"max_ticket_len\": {},",
        MAX_TICKET_LEN
    )
    .ok();
    writeln!(contents, "    }},").ok();

    writeln!(contents, "    \"ticket_limits\": {{").ok();
    writeln!(
        contents,
        "        \"max_scopes\": {},",
        manifest.ticket_limits.max_scopes
    )
    .ok();
    writeln!(
        contents,
        "        \"max_scope_path_len\": {},",
        manifest.ticket_limits.max_scope_path_len
    )
    .ok();
    writeln!(
        contents,
        "        \"max_scope_rate_per_s\": {},",
        manifest.ticket_limits.max_scope_rate_per_s
    )
    .ok();
    writeln!(
        contents,
        "        \"bandwidth_bytes\": {},",
        manifest.ticket_limits.bandwidth_bytes
    )
    .ok();
    writeln!(
        contents,
        "        \"cursor_resumes\": {},",
        manifest.ticket_limits.cursor_resumes
    )
    .ok();
    writeln!(
        contents,
        "        \"cursor_advances\": {},",
        manifest.ticket_limits.cursor_advances
    )
    .ok();
    writeln!(contents, "    }},").ok();

    writeln!(contents, "    \"paths\": {{").ok();
    writeln!(
        contents,
        "        \"queen_ctl\": \"{}\",",
        escape_py_string(&manifest.client_paths.queen_ctl)
    )
    .ok();
    writeln!(
        contents,
        "        \"queen_lifecycle_ctl\": \"{}\",",
        escape_py_string(&manifest.client_paths.queen_lifecycle_ctl)
    )
    .ok();
    writeln!(
        contents,
        "        \"log\": \"{}\",",
        escape_py_string(&manifest.client_paths.log)
    )
    .ok();
    writeln!(contents, "    }},").ok();

    writeln!(contents, "    \"telemetry_ingest\": {{").ok();
    writeln!(
        contents,
        "        \"max_segments_per_device\": {},",
        manifest.telemetry_ingest.max_segments_per_device
    )
    .ok();
    writeln!(
        contents,
        "        \"max_bytes_per_segment\": {},",
        manifest.telemetry_ingest.max_bytes_per_segment
    )
    .ok();
    writeln!(
        contents,
        "        \"max_total_bytes_per_device\": {},",
        manifest.telemetry_ingest.max_total_bytes_per_device
    )
    .ok();
    writeln!(
        contents,
        "        \"eviction_policy\": \"{}\",",
        format_ingest_eviction_policy(&manifest.telemetry_ingest.eviction_policy)
    )
    .ok();
    writeln!(contents, "    }},").ok();

    writeln!(contents, "    \"telemetry_push\": {{").ok();
    writeln!(
        contents,
        "        \"schema\": \"{}\",",
        TELEMETRY_PUSH_SCHEMA
    )
    .ok();
    writeln!(
        contents,
        "        \"max_record_bytes\": {},",
        TELEMETRY_RECORD_MAX_BYTES
    )
    .ok();
    writeln!(contents, "    }},").ok();

    writeln!(contents, "    \"coh\": {{").ok();
    writeln!(contents, "        \"mount\": {{").ok();
    writeln!(
        contents,
        "            \"root\": \"{}\",",
        escape_py_string(&manifest.client_policies.coh.mount.root)
    )
    .ok();
    writeln!(contents, "            \"allowlist\": [").ok();
    for (idx, entry) in manifest
        .client_policies
        .coh
        .mount
        .allowlist
        .iter()
        .enumerate()
    {
        let suffix = if idx + 1 == manifest.client_policies.coh.mount.allowlist.len() {
            ""
        } else {
            ","
        };
        writeln!(
            contents,
            "                \"{}\"{}",
            escape_py_string(entry),
            suffix
        )
        .ok();
    }
    writeln!(contents, "            ]").ok();
    writeln!(contents, "        }},").ok();
    writeln!(contents, "        \"telemetry\": {{").ok();
    writeln!(
        contents,
        "            \"root\": \"{}\",",
        escape_py_string(&manifest.client_policies.coh.telemetry.root)
    )
    .ok();
    writeln!(
        contents,
        "            \"max_devices\": {},",
        manifest.client_policies.coh.telemetry.max_devices
    )
    .ok();
    writeln!(
        contents,
        "            \"max_segments_per_device\": {},",
        manifest.client_policies.coh.telemetry.max_segments_per_device
    )
    .ok();
    writeln!(
        contents,
        "            \"max_bytes_per_segment\": {},",
        manifest.client_policies.coh.telemetry.max_bytes_per_segment
    )
    .ok();
    writeln!(
        contents,
        "            \"max_total_bytes_per_device\": {},",
        manifest.client_policies.coh.telemetry.max_total_bytes_per_device
    )
    .ok();
    writeln!(contents, "        }},").ok();
    writeln!(contents, "        \"run\": {{").ok();
    writeln!(contents, "            \"lease\": {{").ok();
    writeln!(
        contents,
        "                \"schema\": \"{}\",",
        escape_py_string(&manifest.client_policies.coh.run.lease.schema)
    )
    .ok();
    writeln!(
        contents,
        "                \"active_state\": \"{}\",",
        escape_py_string(&manifest.client_policies.coh.run.lease.active_state)
    )
    .ok();
    writeln!(
        contents,
        "                \"max_bytes\": {},",
        manifest.client_policies.coh.run.lease.max_bytes
    )
    .ok();
    writeln!(contents, "            }},").ok();
    writeln!(contents, "            \"breadcrumb\": {{").ok();
    writeln!(
        contents,
        "                \"schema\": \"{}\",",
        escape_py_string(&manifest.client_policies.coh.run.breadcrumb.schema)
    )
    .ok();
    writeln!(
        contents,
        "                \"max_line_bytes\": {},",
        manifest.client_policies.coh.run.breadcrumb.max_line_bytes
    )
    .ok();
    writeln!(
        contents,
        "                \"max_command_bytes\": {},",
        manifest.client_policies.coh.run.breadcrumb.max_command_bytes
    )
    .ok();
    writeln!(contents, "            }},").ok();
    writeln!(contents, "        }},").ok();
    writeln!(contents, "        \"peft\": {{").ok();
    writeln!(contents, "            \"export\": {{").ok();
    writeln!(
        contents,
        "                \"root\": \"{}\",",
        escape_py_string(&manifest.client_policies.coh.peft.export.root)
    )
    .ok();
    writeln!(
        contents,
        "                \"max_telemetry_bytes\": {},",
        manifest.client_policies.coh.peft.export.max_telemetry_bytes
    )
    .ok();
    writeln!(
        contents,
        "                \"max_policy_bytes\": {},",
        manifest.client_policies.coh.peft.export.max_policy_bytes
    )
    .ok();
    writeln!(
        contents,
        "                \"max_base_model_bytes\": {},",
        manifest.client_policies.coh.peft.export.max_base_model_bytes
    )
    .ok();
    writeln!(contents, "            }},").ok();
    writeln!(contents, "            \"import\": {{").ok();
    writeln!(
        contents,
        "                \"registry_root\": \"{}\",",
        escape_py_string(&manifest.client_policies.coh.peft.import.registry_root)
    )
    .ok();
    writeln!(
        contents,
        "                \"max_adapter_bytes\": {},",
        manifest.client_policies.coh.peft.import.max_adapter_bytes
    )
    .ok();
    writeln!(
        contents,
        "                \"max_lora_bytes\": {},",
        manifest.client_policies.coh.peft.import.max_lora_bytes
    )
    .ok();
    writeln!(
        contents,
        "                \"max_metrics_bytes\": {},",
        manifest.client_policies.coh.peft.import.max_metrics_bytes
    )
    .ok();
    writeln!(
        contents,
        "                \"max_manifest_bytes\": {},",
        manifest.client_policies.coh.peft.import.max_manifest_bytes
    )
    .ok();
    writeln!(contents, "            }},").ok();
    writeln!(contents, "            \"activate\": {{").ok();
    writeln!(
        contents,
        "                \"max_model_id_bytes\": {},",
        manifest.client_policies.coh.peft.activate.max_model_id_bytes
    )
    .ok();
    writeln!(
        contents,
        "                \"max_state_bytes\": {},",
        manifest.client_policies.coh.peft.activate.max_state_bytes
    )
    .ok();
    writeln!(contents, "            }},").ok();
    writeln!(contents, "        }},").ok();
    writeln!(contents, "    }},").ok();

    writeln!(contents, "    \"retry\": {{").ok();
    writeln!(
        contents,
        "        \"max_attempts\": {},",
        manifest.client_policies.retry.max_attempts
    )
    .ok();
    writeln!(
        contents,
        "        \"backoff_ms\": {},",
        manifest.client_policies.retry.backoff_ms
    )
    .ok();
    writeln!(
        contents,
        "        \"ceiling_ms\": {},",
        manifest.client_policies.retry.ceiling_ms
    )
    .ok();
    writeln!(
        contents,
        "        \"timeout_ms\": {},",
        manifest.client_policies.retry.timeout_ms
    )
    .ok();
    writeln!(contents, "    }},").ok();

    writeln!(contents, "    \"examples\": {{").ok();
    writeln!(contents, "        \"gpu_id\": \"GPU-0\",").ok();
    writeln!(contents, "        \"mig_gpu_id\": \"MIG-0\",").ok();
    writeln!(contents, "        \"job_id\": \"job_8932\",").ok();
    writeln!(contents, "        \"model_id\": \"llama3-edge-v7\",").ok();
    writeln!(contents, "        \"device_id\": \"device-1\",").ok();
    writeln!(contents, "        \"output_root\": \"out/examples\",").ok();
    writeln!(contents, "    }},").ok();
    writeln!(contents, "}}").ok();

    let hash = hash_bytes(contents.as_bytes());
    CohesixPyDefaults { python: contents, hash }
}

/// Write the generated defaults module to disk.
pub fn emit_defaults(defaults: &CohesixPyDefaults, path: &Path) -> Result<()> {
    fs::write(path, &defaults.python)
        .with_context(|| format!("failed to write cohesix python defaults {}", path.display()))
}

fn escape_py_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn format_ingest_eviction_policy(policy: &TelemetryIngestEvictionPolicy) -> &'static str {
    match policy {
        TelemetryIngestEvictionPolicy::Refuse => "refuse",
        TelemetryIngestEvictionPolicy::EvictOldest => "evict-oldest",
    }
}
