// Copyright © 2025 Lukas Bower
// SPDX-License-Identifier: Apache-2.0
// Purpose: Emit SwarmUI defaults derived from the root-task manifest.
// Author: Lukas Bower

use crate::codegen::hash_bytes;
use crate::ir::Manifest;
use anyhow::{Context, Result};
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug)]
pub struct SwarmUiDefaultsArtifacts {
    pub defaults_toml: PathBuf,
    pub defaults_hash: PathBuf,
    pub defaults_rust: PathBuf,
    pub defaults_doc: PathBuf,
}

pub fn emit_swarmui_defaults(
    manifest: &Manifest,
    manifest_hash: &str,
    defaults_toml_out: &Path,
    defaults_rust_out: &Path,
    defaults_doc_out: &Path,
) -> Result<SwarmUiDefaultsArtifacts> {
    let defaults_toml = render_defaults_toml(manifest, manifest_hash);
    fs::write(defaults_toml_out, &defaults_toml).with_context(|| {
        format!(
            "failed to write swarmui defaults {}",
            defaults_toml_out.display()
        )
    })?;

    let defaults_hash_value = hash_bytes(defaults_toml.as_bytes());
    let defaults_hash_path = defaults_toml_out.with_extension("toml.sha256");
    let hash_contents = format!(
        "# Author: Lukas Bower\n# Purpose: SHA-256 fingerprint for swarmui_defaults.toml.\n{}  {}\n",
        defaults_hash_value,
        defaults_toml_out
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or("swarmui_defaults.toml")
    );
    fs::write(&defaults_hash_path, hash_contents).with_context(|| {
        format!(
            "failed to write swarmui defaults hash {}",
            defaults_hash_path.display()
        )
    })?;

    let defaults_rust = render_defaults_rust(manifest, manifest_hash);
    fs::write(defaults_rust_out, defaults_rust).with_context(|| {
        format!(
            "failed to write swarmui defaults rust {}",
            defaults_rust_out.display()
        )
    })?;

    let defaults_doc = render_defaults_doc(manifest, manifest_hash, &defaults_hash_value);
    fs::write(defaults_doc_out, defaults_doc).with_context(|| {
        format!(
            "failed to write swarmui defaults doc {}",
            defaults_doc_out.display()
        )
    })?;

    Ok(SwarmUiDefaultsArtifacts {
        defaults_toml: defaults_toml_out.to_path_buf(),
        defaults_hash: defaults_hash_path,
        defaults_rust: defaults_rust_out.to_path_buf(),
        defaults_doc: defaults_doc_out.to_path_buf(),
    })
}

fn render_defaults_toml(manifest: &Manifest, manifest_hash: &str) -> String {
    let mut contents = String::new();
    writeln!(contents, "# Author: Lukas Bower").ok();
    writeln!(
        contents,
        "# Purpose: Generated SwarmUI defaults derived from configs/root_task.toml."
    )
    .ok();
    writeln!(contents, "[meta]").ok();
    writeln!(contents, "manifest_sha256 = \"{}\"", manifest_hash).ok();
    writeln!(contents).ok();
    writeln!(contents, "[swarmui]").ok();
    writeln!(
        contents,
        "ticket_scope = \"{}\"",
        manifest.swarmui.ticket_scope.as_str()
    )
    .ok();
    writeln!(contents).ok();
    writeln!(contents, "[swarmui.cache]").ok();
    writeln!(contents, "enabled = {}", manifest.swarmui.cache.enabled).ok();
    writeln!(
        contents,
        "max_bytes = {}",
        manifest.swarmui.cache.max_bytes
    )
    .ok();
    writeln!(contents, "ttl_s = {}", manifest.swarmui.cache.ttl_s).ok();
    writeln!(contents).ok();
    writeln!(contents, "[swarmui.paths]").ok();
    writeln!(
        contents,
        "telemetry_root = \"{}\"",
        manifest.swarmui.paths.telemetry_root
    )
    .ok();
    writeln!(
        contents,
        "proc_ingest_root = \"{}\"",
        manifest.swarmui.paths.proc_ingest_root
    )
    .ok();
    writeln!(
        contents,
        "worker_root = \"{}\"",
        manifest.swarmui.paths.worker_root
    )
    .ok();
    let roots = manifest
        .swarmui
        .paths
        .namespace_roots
        .iter()
        .map(|value| format!("\"{value}\""))
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(contents, "namespace_roots = [{roots}]").ok();
    contents
}

fn render_defaults_rust(manifest: &Manifest, manifest_hash: &str) -> String {
    let mut contents = String::new();
    writeln!(contents, "// Author: Lukas Bower").ok();
    writeln!(
        contents,
        "// Purpose: Generated SwarmUI defaults derived from configs/root_task.toml."
    )
    .ok();
    writeln!(contents, "// @generated by coh-rtc; do not edit.").ok();
    writeln!(contents).ok();
    writeln!(contents, "#![allow(dead_code)]").ok();
    writeln!(contents).ok();
    writeln!(contents, "pub const MANIFEST_SHA256: &str = \"{manifest_hash}\";").ok();
    writeln!(
        contents,
        "pub const SECURE9P_MSIZE: u32 = {};",
        manifest.secure9p.msize
    )
    .ok();
    writeln!(
        contents,
        "pub const SECURE9P_WALK_DEPTH: u8 = {};",
        manifest.secure9p.walk_depth
    )
    .ok();
    writeln!(
        contents,
        "pub const SWARMUI_TICKET_SCOPE: &str = \"{}\";",
        manifest.swarmui.ticket_scope.as_str()
    )
    .ok();
    writeln!(
        contents,
        "pub const SWARMUI_CACHE_ENABLED: bool = {};",
        manifest.swarmui.cache.enabled
    )
    .ok();
    writeln!(
        contents,
        "pub const SWARMUI_CACHE_MAX_BYTES: u32 = {};",
        manifest.swarmui.cache.max_bytes
    )
    .ok();
    writeln!(
        contents,
        "pub const SWARMUI_CACHE_TTL_SECS: u64 = {};",
        manifest.swarmui.cache.ttl_s
    )
    .ok();
    writeln!(
        contents,
        "pub const SWARMUI_TELEMETRY_ROOT: &str = \"{}\";",
        manifest.swarmui.paths.telemetry_root
    )
    .ok();
    writeln!(
        contents,
        "pub const SWARMUI_PROC_INGEST_ROOT: &str = \"{}\";",
        manifest.swarmui.paths.proc_ingest_root
    )
    .ok();
    writeln!(
        contents,
        "pub const SWARMUI_WORKER_ROOT: &str = \"{}\";",
        manifest.swarmui.paths.worker_root
    )
    .ok();
    writeln!(contents, "pub const SWARMUI_NAMESPACE_ROOTS: &[&str] = &[").ok();
    for root in &manifest.swarmui.paths.namespace_roots {
        writeln!(contents, "    \"{root}\",").ok();
    }
    writeln!(contents, "];").ok();
    contents
}

fn render_defaults_doc(manifest: &Manifest, manifest_hash: &str, defaults_hash: &str) -> String {
    let mut contents = String::new();
    writeln!(contents, "<!-- Author: Lukas Bower -->").ok();
    writeln!(
        contents,
        "<!-- Purpose: Generated SwarmUI defaults snippet consumed by docs/USERLAND_AND_CLI.md. -->"
    )
    .ok();
    writeln!(contents).ok();
    writeln!(contents, "### SwarmUI defaults (generated)").ok();
    writeln!(contents, "- `manifest.sha256`: `{manifest_hash}`").ok();
    writeln!(contents, "- `swarmui.defaults.sha256`: `{defaults_hash}`").ok();
    writeln!(
        contents,
        "- `swarmui.ticket_scope`: `{}`",
        manifest.swarmui.ticket_scope.as_str()
    )
    .ok();
    writeln!(
        contents,
        "- `swarmui.cache.enabled`: `{}`",
        manifest.swarmui.cache.enabled
    )
    .ok();
    writeln!(
        contents,
        "- `swarmui.cache.max_bytes`: `{}`",
        manifest.swarmui.cache.max_bytes
    )
    .ok();
    writeln!(
        contents,
        "- `swarmui.cache.ttl_s`: `{}`",
        manifest.swarmui.cache.ttl_s
    )
    .ok();
    writeln!(
        contents,
        "- `swarmui.paths.telemetry_root`: `{}`",
        manifest.swarmui.paths.telemetry_root
    )
    .ok();
    writeln!(
        contents,
        "- `swarmui.paths.proc_ingest_root`: `{}`",
        manifest.swarmui.paths.proc_ingest_root
    )
    .ok();
    writeln!(
        contents,
        "- `swarmui.paths.worker_root`: `{}`",
        manifest.swarmui.paths.worker_root
    )
    .ok();
    writeln!(
        contents,
        "- `swarmui.paths.namespace_roots`: `{}`",
        manifest.swarmui.paths.namespace_roots.join(", ")
    )
    .ok();
    writeln!(contents).ok();
    writeln!(
        contents,
        "_Generated from `configs/root_task.toml` (sha256: `{manifest_hash}`)._"
    )
    .ok();
    contents
}
