#!/usr/bin/env bash
# CLASSIFICATION: COMMUNITY
# Filename: simulate_batch.sh v0.1
# Author: Lukas Bower
# Date Modified: 2029-01-26
set -euo pipefail

usage() {
  cat <<'USAGE'
Usage: tools/simulate_batch.sh [options]

Generate mock batch inputs (documents, manifest, hydration log) for Cohesix dry runs.

Options:
  -h, --help           Show this help message and exit
  --size N             Number of documents to generate (default: 5)
  --origin URI         Batch origin identifier (default: mock://simulate)
  --outdir PATH        Directory to create (defaults to TMPDIR-aware temp dir)
  --hydration-log PATH Explicit hydration log path (default: <outdir>/hydration.log)
  --quiet              Only print essential information
USAGE
}

log() {
  if [[ ${QUIET:-0} -eq 0 ]]; then
    printf '[simulate-batch] %s\n' "$1"
  fi
}

warn() {
  printf '[simulate-batch][warn] %s\n' "$1" >&2
}

select_tmp_root() {
  local candidate
  for candidate in "${COHESIX_ENS_TMP:-}" "${COHESIX_TRACE_TMP:-}" "${TMPDIR:-}"; do
    if [[ -n "$candidate" ]]; then
      printf '%s' "$candidate"
      return 0
    fi
  done
  mktemp -d
}

SIZE=5
ORIGIN="mock://simulate"
OUTDIR=""
HYDRATION_LOG=""
QUIET=0

while (($#)); do
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    --size)
      if [[ $# -lt 2 ]]; then
        warn "--size requires an integer argument"
        exit 1
      fi
      SIZE="$2"
      shift 2
      ;;
    --origin)
      if [[ $# -lt 2 ]]; then
        warn "--origin requires a value"
        exit 1
      fi
      ORIGIN="$2"
      shift 2
      ;;
    --outdir)
      if [[ $# -lt 2 ]]; then
        warn "--outdir requires a directory path"
        exit 1
      fi
      OUTDIR="$2"
      shift 2
      ;;
    --hydration-log)
      if [[ $# -lt 2 ]]; then
        warn "--hydration-log requires a file path"
        exit 1
      fi
      HYDRATION_LOG="$2"
      shift 2
      ;;
    --quiet)
      QUIET=1
      shift
      ;;
    --)
      shift
      break
      ;;
    -* )
      warn "Unknown option: $1"
      usage
      exit 1
      ;;
    *)
      warn "Unexpected positional argument: $1"
      usage
      exit 1
      ;;
  esac
done

if (( $# )); then
  warn "Unexpected arguments: $*"
  usage
  exit 1
fi

if ! [[ "$SIZE" =~ ^[0-9]+$ ]] || [[ "$SIZE" -le 0 ]]; then
  warn "--size must be a positive integer"
  exit 1
fi

if [[ -z "$OUTDIR" ]]; then
  base="$(select_tmp_root)"
  mkdir -p "$base/cohesix_sim_batches"
  OUTDIR="$(mktemp -d "$base/cohesix_sim_batches/sim.XXXXXX")"
else
  mkdir -p "$OUTDIR"
fi

if [[ -z "$HYDRATION_LOG" ]]; then
  HYDRATION_LOG="$OUTDIR/hydration.log"
fi

DOCS_DIR="$OUTDIR/docs"
STAGING_DIR="$OUTDIR/staging"
LOGS_DIR="$OUTDIR/logs"
MANIFEST_PATH="$OUTDIR/manifest.json"
METADATA_PATH="$OUTDIR/METADATA.md"
DATE_STAMP="$(date +%Y-%m-%d)"

mkdir -p "$DOCS_DIR" "$STAGING_DIR" "$LOGS_DIR"

DOC_LIST=()
for (( idx=1; idx<=SIZE; idx++ )); do
  printf -v doc_name 'DOCUMENT_%02d.md' "$idx"
  doc_path="$DOCS_DIR/$doc_name"
  cat <<DOC > "$doc_path"
// CLASSIFICATION: COMMUNITY
// Filename: $doc_name v0.1
// Author: Lukas Bower
// Date Modified: $DATE_STAMP

# Simulated Document $idx

This file was generated by simulate_batch.sh. Batch origin: $ORIGIN.
DOC
  DOC_LIST+=("$doc_name")
  log "Created $doc_path"
done

python3 - "$MANIFEST_PATH" "$ORIGIN" "$SIZE" "${DOC_LIST[@]}" <<'PY'
import json
import sys
from pathlib import Path

manifest_path = Path(sys.argv[1])
origin = sys.argv[2]
size = int(sys.argv[3])
docs = sys.argv[4:]

manifest = {
    "batch_origin": origin,
    "batch_size": size,
    "documents": [
        {
            "path": f"docs/{name}",
            "status": "pending",
        }
        for name in docs
    ],
}
manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
PY

cat <<HDR > "$METADATA_PATH"
// CLASSIFICATION: COMMUNITY
// Filename: METADATA.md v0.1
// Author: Lukas Bower
// Date Modified: $DATE_STAMP

| Filename           | Version | Last Modified | Classification | BATCH_SIZE | BATCH_ORIGIN |
|--------------------|---------|---------------|----------------|------------|--------------|
HDR
for doc_name in "${DOC_LIST[@]}"; do
  printf '| %-18s | %-7s | %-13s | %-14s | %-10s | %-12s |\n' "$doc_name" "v0.1" "$DATE_STAMP" "COMMUNITY" "" "" >> "$METADATA_PATH"
done

echo "# Cohesix Hydration Log" > "$HYDRATION_LOG"
echo "ENV|BATCH_ORIGIN|$ORIGIN" >> "$HYDRATION_LOG"
echo "CWD|$DOCS_DIR" >> "$HYDRATION_LOG"
for doc_name in "${DOC_LIST[@]}"; do
  echo "RUN|echo|hydrate|$doc_name" >> "$HYDRATION_LOG"
  echo "COPY|$doc_name|$STAGING_DIR/$doc_name" >> "$HYDRATION_LOG"
  echo "SLEEP|0.05" >> "$HYDRATION_LOG"
done
echo "CWD|$OUTDIR" >> "$HYDRATION_LOG"

echo "Batch Origin: $ORIGIN" > "$LOGS_DIR/batch_info.txt"
echo "Batch Size: $SIZE" >> "$LOGS_DIR/batch_info.txt"

log "Manifest      : $MANIFEST_PATH"
log "Metadata Table: $METADATA_PATH"
log "Hydration Log : $HYDRATION_LOG"
log "Staging Dir   : $STAGING_DIR"

echo "BATCH_DIR=$OUTDIR"
