/*
 * Copyright 2020, Data61, CSIRO (ABN 41 687 119 230)
 *
 * SPDX-License-Identifier: GPL-2.0-only
 */


/* This header was generated by kernel/tools/syscall_header_gen.py.
 *
 * To add a system call number, edit kernel/libsel4/include/api/syscall.xml
 *
 */
#pragma once

#ifdef __ASSEMBLER__

/* System Calls */
#define SYSCALL_CALL (-1)
#define SYSCALL_REPLY_RECV (-2)
#define SYSCALL_SEND (-3)
#define SYSCALL_NB_SEND (-4)
#define SYSCALL_RECV (-5)
#define SYSCALL_REPLY (-6)
#define SYSCALL_YIELD (-7)
#define SYSCALL_NB_RECV (-8)

#endif /* __ASSEMBLER__ */

#define SYSCALL_MAX (-1)
#define SYSCALL_MIN (-8)

#ifndef __ASSEMBLER__

enum syscall {
    SysCall = -1,
    SysReplyRecv = -2,
    SysSend = -3,
    SysNBSend = -4,
    SysRecv = -5,
    SysReply = -6,
    SysYield = -7,
    SysNBRecv = -8,
#if defined(CONFIG_PRINTING)
    SysDebugPutChar = -9,
    SysDebugDumpScheduler = -10,
#endif /* defined(CONFIG_PRINTING) */
#if defined(CONFIG_DEBUG_BUILD)
    SysDebugHalt = -11,
    SysDebugCapIdentify = -12,
    SysDebugSnapshot = -13,
    SysDebugNameThread = -14,
#endif /* defined(CONFIG_DEBUG_BUILD) */
#if (defined(CONFIG_DEBUG_BUILD) && defined(CONFIG_ENABLE_SMP_SUPPORT))
    SysDebugSendIPI = -15,
    SysDebugGetThreadAffinity = -16,
#endif /* (defined(CONFIG_DEBUG_BUILD) && defined(CONFIG_ENABLE_SMP_SUPPORT)) */
#if defined(CONFIG_DANGEROUS_CODE_INJECTION)
    SysDebugRun = -17,
#endif /* defined(CONFIG_DANGEROUS_CODE_INJECTION) */
#if defined(CONFIG_ENABLE_BENCHMARKS)
    SysBenchmarkFlushCaches = -18,
    SysBenchmarkResetLog = -19,
    SysBenchmarkFinalizeLog = -20,
    SysBenchmarkSetLogBuffer = -21,
    SysBenchmarkNullSyscall = -22,
#endif /* defined(CONFIG_ENABLE_BENCHMARKS) */
#if defined(CONFIG_BENCHMARK_TRACK_UTILISATION)
    SysBenchmarkGetThreadUtilisation = -23,
    SysBenchmarkResetThreadUtilisation = -24,
#endif /* defined(CONFIG_BENCHMARK_TRACK_UTILISATION) */
#if (defined(CONFIG_DEBUG_BUILD) && defined(CONFIG_BENCHMARK_TRACK_UTILISATION))
    SysBenchmarkDumpAllThreadsUtilisation = -25,
    SysBenchmarkResetAllThreadsUtilisation = -26,
#endif /* (defined(CONFIG_DEBUG_BUILD) && defined(CONFIG_BENCHMARK_TRACK_UTILISATION)) */
#if defined(CONFIG_KERNEL_X86_DANGEROUS_MSR)
    SysX86DangerousWRMSR = -27,
    SysX86DangerousRDMSR = -28,
#endif /* defined(CONFIG_KERNEL_X86_DANGEROUS_MSR) */
#if defined(CONFIG_VTX)
    SysVMEnter = -29,
#endif /* defined(CONFIG_VTX) */
#if defined(CONFIG_SET_TLS_BASE_SELF)
    SysSetTLSBase = -30,
#endif /* defined(CONFIG_SET_TLS_BASE_SELF) */
};
typedef word_t syscall_t;

/* System call names */
#ifdef CONFIG_DEBUG_BUILD
static char *syscall_names[] UNUSED = {
         [1] = "Call",
         [2] = "ReplyRecv",
         [3] = "Send",
         [4] = "NBSend",
         [5] = "Recv",
         [6] = "Reply",
         [7] = "Yield",
         [8] = "NBRecv",
};
#endif /* CONFIG_DEBUG_BUILD */
#endif /* !__ASSEMBLER__ */
