// Author: Lukas Bower
// Purpose: Generated SwarmUI defaults derived from configs/root_task.toml.
// @generated by coh-rtc; do not edit.

#![allow(dead_code)]

pub const MANIFEST_SHA256: &str = "6b2cb0b8a80b57f75acb5049fe17f2aae92e0d7adf690b34fc30eb01b084710c";
pub const SECURE9P_MSIZE: u32 = 8192;
pub const SECURE9P_WALK_DEPTH: u8 = 8;
pub const SWARMUI_TICKET_SCOPE: &str = "per-ticket";
pub const SWARMUI_CACHE_ENABLED: bool = false;
pub const SWARMUI_CACHE_MAX_BYTES: u32 = 262144;
pub const SWARMUI_CACHE_TTL_SECS: u64 = 3600;
pub const SWARMUI_HIVE_FRAME_CAP_FPS: u16 = 60;
pub const SWARMUI_HIVE_STEP_MS: u16 = 16;
pub const SWARMUI_HIVE_LOD_ZOOM_OUT: f32 = 0.7;
pub const SWARMUI_HIVE_LOD_ZOOM_IN: f32 = 1.25;
pub const SWARMUI_HIVE_LOD_EVENT_BUDGET: u32 = 512;
pub const SWARMUI_HIVE_SNAPSHOT_MAX_EVENTS: u32 = 4096;
pub const SWARMUI_TELEMETRY_ROOT: &str = "/worker";
pub const SWARMUI_PROC_INGEST_ROOT: &str = "/proc/ingest";
pub const SWARMUI_WORKER_ROOT: &str = "/worker";
pub const SWARMUI_NAMESPACE_ROOTS: &[&str] = &[
    "/proc",
    "/queen",
    "/worker",
    "/log",
    "/gpu",
];
