// Author: Lukas Bower
// Purpose: Generated SwarmUI defaults derived from configs/root_task.toml.
// Copyright 2026 Lukas Bower
// @generated by coh-rtc; do not edit.

#![allow(dead_code)]

pub const MANIFEST_SHA256: &str =
    "e41ab0cde0b198fedf6c6055ada5e94dafcc938dff9e174f3b3226b59cf1e1db";
pub const SECURE9P_MSIZE: u32 = 8192;
pub const SECURE9P_WALK_DEPTH: u8 = 8;
pub const SWARMUI_TICKET_SCOPE: &str = "per-ticket";
pub const SWARMUI_CACHE_ENABLED: bool = false;
pub const SWARMUI_CACHE_MAX_BYTES: u32 = 262144;
pub const SWARMUI_CACHE_TTL_SECS: u64 = 3600;
pub const SWARMUI_HIVE_FRAME_CAP_FPS: u16 = 30;
pub const SWARMUI_HIVE_STEP_MS: u16 = 16;
pub const SWARMUI_HIVE_LOD_ZOOM_OUT: f32 = 0.7;
pub const SWARMUI_HIVE_LOD_ZOOM_IN: f32 = 1.25;
pub const SWARMUI_HIVE_LOD_EVENT_BUDGET: u32 = 512;
pub const SWARMUI_HIVE_SNAPSHOT_MAX_EVENTS: u32 = 4096;
pub const SWARMUI_HIVE_OVERLAY_LINES: u16 = 3;
pub const SWARMUI_HIVE_DETAIL_LINES: u16 = 50;
pub const SWARMUI_HIVE_LINE_CAP_BYTES: u32 = 160;
pub const SWARMUI_HIVE_PER_WORKER_BYTES: u32 = 2048;
pub const SWARMUI_HIVE_PENDING_LINES_PER_WORKER: u16 = 64;
pub const SWARMUI_HIVE_PENDING_EVENT_CAP: u32 = 4096;
pub const SWARMUI_HIVE_POLL_WORKERS_PER_TICK: u16 = 32;
pub const SWARMUI_HIVE_STATUS_POLL_MS: u32 = 500;
pub const SWARMUI_HIVE_DEGRADE_PRESSURE: f32 = 1.0;
pub const SWARMUI_TRACE_MAX_BYTES: u32 = 1048576;
pub const SWARMUI_TELEMETRY_ROOT: &str = "/worker";
pub const SWARMUI_PROC_INGEST_ROOT: &str = "/proc/ingest";
pub const SWARMUI_WORKER_ROOT: &str = "/worker";
pub const SWARMUI_NAMESPACE_ROOTS: &[&str] = &["/proc", "/queen", "/worker", "/log", "/gpu"];
